// flow-typed signature: 2cfa2883b73683fe51192834f146d980
// flow-typed version: <<STUB>>/@prismicio/client_v5.1.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@prismicio/client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@prismicio/client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@prismicio/client/cjs/@prismicio/client' {
  declare module.exports: any;
}

declare module '@prismicio/client/cjs/@prismicio/client.min' {
  declare module.exports: any;
}

declare module '@prismicio/client/cjs/prismic-javascript' {
  declare module.exports: any;
}

declare module '@prismicio/client/cjs/prismic-javascript.min' {
  declare module.exports: any;
}

declare module '@prismicio/client/umd/@prismicio/client' {
  declare module.exports: any;
}

declare module '@prismicio/client/umd/@prismicio/client.min' {
  declare module.exports: any;
}

declare module '@prismicio/client/umd/prismic-javascript' {
  declare module.exports: any;
}

declare module '@prismicio/client/umd/prismic-javascript.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@prismicio/client/cjs/@prismicio/client.js' {
  declare module.exports: $Exports<'@prismicio/client/cjs/@prismicio/client'>;
}
declare module '@prismicio/client/cjs/@prismicio/client.min.js' {
  declare module.exports: $Exports<'@prismicio/client/cjs/@prismicio/client.min'>;
}
declare module '@prismicio/client/cjs/prismic-javascript.js' {
  declare module.exports: $Exports<'@prismicio/client/cjs/prismic-javascript'>;
}
declare module '@prismicio/client/cjs/prismic-javascript.min.js' {
  declare module.exports: $Exports<'@prismicio/client/cjs/prismic-javascript.min'>;
}
declare module '@prismicio/client/umd/@prismicio/client.js' {
  declare module.exports: $Exports<'@prismicio/client/umd/@prismicio/client'>;
}
declare module '@prismicio/client/umd/@prismicio/client.min.js' {
  declare module.exports: $Exports<'@prismicio/client/umd/@prismicio/client.min'>;
}
declare module '@prismicio/client/umd/prismic-javascript.js' {
  declare module.exports: $Exports<'@prismicio/client/umd/prismic-javascript'>;
}
declare module '@prismicio/client/umd/prismic-javascript.min.js' {
  declare module.exports: $Exports<'@prismicio/client/umd/prismic-javascript.min'>;
}
