name: Transporter
handle: transporter
display:
  background: "#eeebe2"
context:
  title: Latest articles
  promos:
  - modifiers: ['transporter-child']
    headingLevel: h3
    url: http://google.com
    image:
      sources:
      - src: https://placehold.it/1200x900
        size: '1200'
      - src: https://placehold.it/900x600
        size: '900'
      - src: https://placehold.it/450x300
        size: '450'
      alt: placeholder image
    meta: 
      type:
      date: 2 days ago
    title: Oops!...I wrote a Britney blog post
    copy:
  - modifiers: ['transporter-child']
    headingLevel: h3
    url: http://google.com
    image:
      sources:
      - src: https://placehold.it/1200x900
        size: '1200'
      - src: https://placehold.it/900x600
        size: '900'
      - src: https://placehold.it/450x300
        size: '450'
      alt: placeholder image
    meta: 
      type:
      date: 2 days ago
    title: Oops!...I wrote a Britney blog post
    copy:
  - modifiers: ['transporter-child']
    headingLevel: h3
    url: http://google.com
    image:
      sources:
      - src: https://placehold.it/1200x900
        size: '1200'
      - src: https://placehold.it/900x600
        size: '900'
      - src: https://placehold.it/450x300
        size: '450'
      alt: placeholder image
    meta: 
      type:
      date: 2 days ago
    title: Oops!...I wrote a Britney blog post
    copy:
  - modifiers: ['transporter-child']
    headingLevel: h3
    url: http://google.com
    image:
      sources:
      - src: https://placehold.it/1200x900
        size: '1200'
      - src: https://placehold.it/900x600
        size: '900'
      - src: https://placehold.it/450x300
        size: '450'
      alt: placeholder image
    meta: 
      type:
      date: 2 days ago
    title: Oops!...I wrote a Britney blog post
    copy:
  - modifiers: ['transporter-child']
    headingLevel: h3
    url: http://google.com
    image:
      sources:
      - src: https://placehold.it/1200x900
        size: '1200'
      - src: https://placehold.it/900x600
        size: '900'
      - src: https://placehold.it/450x300
        size: '450'
      alt: placeholder image
    meta: 
      type:
      date: 2 days ago
    title: Oops!...I wrote a Britney blog post
    copy:
  - modifiers: ['transporter-child']
    headingLevel: h3
    url: http://google.com
    image:
      sources:
      - src: https://placehold.it/1200x900
        size: '1200'
      - src: https://placehold.it/900x600
        size: '900'
      - src: https://placehold.it/450x300
        size: '450'
      alt: placeholder image
    meta: 
      type:
      date: 2 days ago
    title: Oops!...I wrote a Britney blog post
    copy:
