// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  audio_player: dynamic(() => import('./AudioPlayer')),
  text: dynamic(() => import('./Text')),
};
