// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  audioPlayer: dynamic(() => import('./AudioPlayer')),
  editorialImage: dynamic(() => import('./EditorialImage')),
  editorialImageGallery: dynamic(() => import('./EditorialImageGallery')),
  quoteV2: dynamic(() => import('./Quote')),
  quote: dynamic(() => import('./Quote')),
  text: dynamic(() => import('./Text')),
};
