// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  TextTest: dynamic(() => import('./TextTest')),
  audioPlayer: dynamic(() => import('./AudioPlayer')),
  collectionVenue: dynamic(() => import('./CollectionVenue')),
  contact: dynamic(() => import('./Contact')),
  contentList: dynamic(() => import('./ContentList')),
  editorialImage: dynamic(() => import('./EditorialImage')),
  editorialImageGallery: dynamic(() => import('./EditorialImageGallery')),
  embed: dynamic(() => import('./Embed')),
  gifVideo: dynamic(() => import('./GifVideo')),
  iframe: dynamic(() => import('./Iframe')),
  infoBlock: dynamic(() => import('./InfoBlock')),
  map: dynamic(() => import('./Map')),
  quote: dynamic(() => import('./Quote')),
  quoteV2: dynamic(() => import('./QuoteV2')),
  searchResults: dynamic(() => import('./SearchResults')),
  standfirst: dynamic(() => import('./Standfirst')),
  tagList: dynamic(() => import('./TagList')),
  text: dynamic(() => import('./Text')),
  textAndIcons: dynamic(() => import('./TextAndIcons')),
  textAndImage: dynamic(() => import('./TextAndImage')),
  titledTextList: dynamic(() => import('./TitledTextList')),
};
