FROM nginx:1.13.8-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY redirects.conf /etc/nginx/redirects.conf
LABEL description="nginx with routing config for wellcomecollection.org and some subdomains."
