// flow-typed signature: ec69f4de2f360f9b019569c9e909348f
// flow-typed version: <<STUB>>/cookie-cutter_v^0.2.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cookie-cutter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cookie-cutter' {
  declare module.exports: any;
}
