// flow-typed signature: 31ea795e1816c1a2196bf992db43af30
// flow-typed version: <<STUB>>/crypto-browserify_v3.12.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crypto-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crypto-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crypto-browserify/example/bundle' {
  declare module.exports: any;
}

declare module 'crypto-browserify/example/test' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/aes' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/create-hash' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/create-hmac' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/dh' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/ecdh' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/node/dh' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/pbkdf2' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/public-encrypt' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/random-bytes' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/random-fill' {
  declare module.exports: any;
}

declare module 'crypto-browserify/test/sign' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crypto-browserify/example/bundle.js' {
  declare module.exports: $Exports<'crypto-browserify/example/bundle'>;
}
declare module 'crypto-browserify/example/test.js' {
  declare module.exports: $Exports<'crypto-browserify/example/test'>;
}
declare module 'crypto-browserify/index' {
  declare module.exports: $Exports<'crypto-browserify'>;
}
declare module 'crypto-browserify/index.js' {
  declare module.exports: $Exports<'crypto-browserify'>;
}
declare module 'crypto-browserify/test/aes.js' {
  declare module.exports: $Exports<'crypto-browserify/test/aes'>;
}
declare module 'crypto-browserify/test/create-hash.js' {
  declare module.exports: $Exports<'crypto-browserify/test/create-hash'>;
}
declare module 'crypto-browserify/test/create-hmac.js' {
  declare module.exports: $Exports<'crypto-browserify/test/create-hmac'>;
}
declare module 'crypto-browserify/test/dh.js' {
  declare module.exports: $Exports<'crypto-browserify/test/dh'>;
}
declare module 'crypto-browserify/test/ecdh.js' {
  declare module.exports: $Exports<'crypto-browserify/test/ecdh'>;
}
declare module 'crypto-browserify/test/index' {
  declare module.exports: $Exports<'crypto-browserify/test'>;
}
declare module 'crypto-browserify/test/index.js' {
  declare module.exports: $Exports<'crypto-browserify/test'>;
}
declare module 'crypto-browserify/test/node/dh.js' {
  declare module.exports: $Exports<'crypto-browserify/test/node/dh'>;
}
declare module 'crypto-browserify/test/pbkdf2.js' {
  declare module.exports: $Exports<'crypto-browserify/test/pbkdf2'>;
}
declare module 'crypto-browserify/test/public-encrypt.js' {
  declare module.exports: $Exports<'crypto-browserify/test/public-encrypt'>;
}
declare module 'crypto-browserify/test/random-bytes.js' {
  declare module.exports: $Exports<'crypto-browserify/test/random-bytes'>;
}
declare module 'crypto-browserify/test/random-fill.js' {
  declare module.exports: $Exports<'crypto-browserify/test/random-fill'>;
}
declare module 'crypto-browserify/test/sign.js' {
  declare module.exports: $Exports<'crypto-browserify/test/sign'>;
}
