// flow-typed signature: 7d7008307e6b005de43533fcf78a6b46
// flow-typed version: <<STUB>>/lazysizes_v4.x.x/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lazysizes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lazysizes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lazysizes/lazysizes-umd' {
  declare module.exports: any;
}

declare module 'lazysizes/lazysizes-umd.min' {
  declare module.exports: any;
}

declare module 'lazysizes/lazysizes' {
  declare module.exports: any;
}

declare module 'lazysizes/lazysizes.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/artdirect/ls.artdirect' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/artdirect/ls.artdirect.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/aspectratio/ls.aspectratio' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/aspectratio/ls.aspectratio.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/attrchange/ls.attrchange' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/attrchange/ls.attrchange.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/bgset/ls.bgset' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/bgset/ls.bgset.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/blur-up/ls.blur-up' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/blur-up/ls.blur-up.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/custommedia/ls.custommedia' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/custommedia/ls.custommedia.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/fix-ios-sizes/fix-ios-sizes' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/fix-ios-sizes/fix-ios-sizes.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/include/ls.include' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/include/ls.include.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/noscript/ls.noscript' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/noscript/ls.noscript.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/object-fit/ls.object-fit' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/object-fit/ls.object-fit.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/optimumx/ls.optimumx' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/optimumx/ls.optimumx.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/parent-fit/ls.parent-fit' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/parent-fit/ls.parent-fit.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/print/ls.print' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/print/ls.print.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/progressive/ls.progressive' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/progressive/ls.progressive.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/respimg/ls.respimg' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/respimg/ls.respimg.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/rias/ls.rias' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/rias/ls.rias.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/static-gecko-picture/ls.static-gecko-picture' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/static-gecko-picture/ls.static-gecko-picture.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/twitter/ls.twitter' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/twitter/ls.twitter.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/unload/ls.unload' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/unload/ls.unload.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/unveilhooks/ls.unveilhooks' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/unveilhooks/ls.unveilhooks.min' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/video-embed/ls.video-embed' {
  declare module.exports: any;
}

declare module 'lazysizes/plugins/video-embed/ls.video-embed.min' {
  declare module.exports: any;
}

declare module 'lazysizes/src/lazysizes-core' {
  declare module.exports: any;
}

declare module 'lazysizes/src/lazysizes-intersection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lazysizes/lazysizes-umd.js' {
  declare module.exports: $Exports<'lazysizes/lazysizes-umd'>;
}
declare module 'lazysizes/lazysizes-umd.min.js' {
  declare module.exports: $Exports<'lazysizes/lazysizes-umd.min'>;
}
declare module 'lazysizes/lazysizes.js' {
  declare module.exports: $Exports<'lazysizes/lazysizes'>;
}
declare module 'lazysizes/lazysizes.min.js' {
  declare module.exports: $Exports<'lazysizes/lazysizes.min'>;
}
declare module 'lazysizes/plugins/artdirect/ls.artdirect.js' {
  declare module.exports: $Exports<'lazysizes/plugins/artdirect/ls.artdirect'>;
}
declare module 'lazysizes/plugins/artdirect/ls.artdirect.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/artdirect/ls.artdirect.min'>;
}
declare module 'lazysizes/plugins/aspectratio/ls.aspectratio.js' {
  declare module.exports: $Exports<'lazysizes/plugins/aspectratio/ls.aspectratio'>;
}
declare module 'lazysizes/plugins/aspectratio/ls.aspectratio.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/aspectratio/ls.aspectratio.min'>;
}
declare module 'lazysizes/plugins/attrchange/ls.attrchange.js' {
  declare module.exports: $Exports<'lazysizes/plugins/attrchange/ls.attrchange'>;
}
declare module 'lazysizes/plugins/attrchange/ls.attrchange.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/attrchange/ls.attrchange.min'>;
}
declare module 'lazysizes/plugins/bgset/ls.bgset.js' {
  declare module.exports: $Exports<'lazysizes/plugins/bgset/ls.bgset'>;
}
declare module 'lazysizes/plugins/bgset/ls.bgset.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/bgset/ls.bgset.min'>;
}
declare module 'lazysizes/plugins/blur-up/ls.blur-up.js' {
  declare module.exports: $Exports<'lazysizes/plugins/blur-up/ls.blur-up'>;
}
declare module 'lazysizes/plugins/blur-up/ls.blur-up.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/blur-up/ls.blur-up.min'>;
}
declare module 'lazysizes/plugins/custommedia/ls.custommedia.js' {
  declare module.exports: $Exports<'lazysizes/plugins/custommedia/ls.custommedia'>;
}
declare module 'lazysizes/plugins/custommedia/ls.custommedia.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/custommedia/ls.custommedia.min'>;
}
declare module 'lazysizes/plugins/fix-ios-sizes/fix-ios-sizes.js' {
  declare module.exports: $Exports<'lazysizes/plugins/fix-ios-sizes/fix-ios-sizes'>;
}
declare module 'lazysizes/plugins/fix-ios-sizes/fix-ios-sizes.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/fix-ios-sizes/fix-ios-sizes.min'>;
}
declare module 'lazysizes/plugins/include/ls.include.js' {
  declare module.exports: $Exports<'lazysizes/plugins/include/ls.include'>;
}
declare module 'lazysizes/plugins/include/ls.include.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/include/ls.include.min'>;
}
declare module 'lazysizes/plugins/noscript/ls.noscript.js' {
  declare module.exports: $Exports<'lazysizes/plugins/noscript/ls.noscript'>;
}
declare module 'lazysizes/plugins/noscript/ls.noscript.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/noscript/ls.noscript.min'>;
}
declare module 'lazysizes/plugins/object-fit/ls.object-fit.js' {
  declare module.exports: $Exports<'lazysizes/plugins/object-fit/ls.object-fit'>;
}
declare module 'lazysizes/plugins/object-fit/ls.object-fit.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/object-fit/ls.object-fit.min'>;
}
declare module 'lazysizes/plugins/optimumx/ls.optimumx.js' {
  declare module.exports: $Exports<'lazysizes/plugins/optimumx/ls.optimumx'>;
}
declare module 'lazysizes/plugins/optimumx/ls.optimumx.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/optimumx/ls.optimumx.min'>;
}
declare module 'lazysizes/plugins/parent-fit/ls.parent-fit.js' {
  declare module.exports: $Exports<'lazysizes/plugins/parent-fit/ls.parent-fit'>;
}
declare module 'lazysizes/plugins/parent-fit/ls.parent-fit.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/parent-fit/ls.parent-fit.min'>;
}
declare module 'lazysizes/plugins/print/ls.print.js' {
  declare module.exports: $Exports<'lazysizes/plugins/print/ls.print'>;
}
declare module 'lazysizes/plugins/print/ls.print.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/print/ls.print.min'>;
}
declare module 'lazysizes/plugins/progressive/ls.progressive.js' {
  declare module.exports: $Exports<'lazysizes/plugins/progressive/ls.progressive'>;
}
declare module 'lazysizes/plugins/progressive/ls.progressive.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/progressive/ls.progressive.min'>;
}
declare module 'lazysizes/plugins/respimg/ls.respimg.js' {
  declare module.exports: $Exports<'lazysizes/plugins/respimg/ls.respimg'>;
}
declare module 'lazysizes/plugins/respimg/ls.respimg.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/respimg/ls.respimg.min'>;
}
declare module 'lazysizes/plugins/rias/ls.rias.js' {
  declare module.exports: $Exports<'lazysizes/plugins/rias/ls.rias'>;
}
declare module 'lazysizes/plugins/rias/ls.rias.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/rias/ls.rias.min'>;
}
declare module 'lazysizes/plugins/static-gecko-picture/ls.static-gecko-picture.js' {
  declare module.exports: $Exports<'lazysizes/plugins/static-gecko-picture/ls.static-gecko-picture'>;
}
declare module 'lazysizes/plugins/static-gecko-picture/ls.static-gecko-picture.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/static-gecko-picture/ls.static-gecko-picture.min'>;
}
declare module 'lazysizes/plugins/twitter/ls.twitter.js' {
  declare module.exports: $Exports<'lazysizes/plugins/twitter/ls.twitter'>;
}
declare module 'lazysizes/plugins/twitter/ls.twitter.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/twitter/ls.twitter.min'>;
}
declare module 'lazysizes/plugins/unload/ls.unload.js' {
  declare module.exports: $Exports<'lazysizes/plugins/unload/ls.unload'>;
}
declare module 'lazysizes/plugins/unload/ls.unload.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/unload/ls.unload.min'>;
}
declare module 'lazysizes/plugins/unveilhooks/ls.unveilhooks.js' {
  declare module.exports: $Exports<'lazysizes/plugins/unveilhooks/ls.unveilhooks'>;
}
declare module 'lazysizes/plugins/unveilhooks/ls.unveilhooks.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/unveilhooks/ls.unveilhooks.min'>;
}
declare module 'lazysizes/plugins/video-embed/ls.video-embed.js' {
  declare module.exports: $Exports<'lazysizes/plugins/video-embed/ls.video-embed'>;
}
declare module 'lazysizes/plugins/video-embed/ls.video-embed.min.js' {
  declare module.exports: $Exports<'lazysizes/plugins/video-embed/ls.video-embed.min'>;
}
declare module 'lazysizes/src/lazysizes-core.js' {
  declare module.exports: $Exports<'lazysizes/src/lazysizes-core'>;
}
declare module 'lazysizes/src/lazysizes-intersection.js' {
  declare module.exports: $Exports<'lazysizes/src/lazysizes-intersection'>;
}
