// flow-typed signature: 9d825067548ae9710390f7e55f6181c5
// flow-typed version: <<STUB>>/lodash.groupby_v^4.6.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.groupby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.groupby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.groupby/index' {
  declare module.exports: $Exports<'lodash.groupby'>;
}
declare module 'lodash.groupby/index.js' {
  declare module.exports: $Exports<'lodash.groupby'>;
}
