// flow-typed signature: 3557a5c456a15cc62f36548bc8a15049
// flow-typed version: <<STUB>>/lodash.flattendeep_v4.4.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.flattendeep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.flattendeep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.flattendeep/index' {
  declare module.exports: $Exports<'lodash.flattendeep'>;
}
declare module 'lodash.flattendeep/index.js' {
  declare module.exports: $Exports<'lodash.flattendeep'>;
}
