// flow-typed signature: c9f8f6a8835c66685eede1107b76f9d4
// flow-typed version: <<STUB>>/next-cookies_v1.0.4/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-cookies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'next-cookies/index' {
  declare module.exports: $Exports<'next-cookies'>;
}
declare module 'next-cookies/index.js' {
  declare module.exports: $Exports<'next-cookies'>;
}
