// flow-typed signature: 8795cc972b8fbe1d2a4d59ec77099ff3
// flow-typed version: <<STUB>>/openseadragon_v2.3.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'openseadragon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'openseadragon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'openseadragon/build/openseadragon/openseadragon' {
  declare module.exports: any;
}

declare module 'openseadragon/build/openseadragon/openseadragon.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'openseadragon/build/openseadragon/openseadragon.js' {
  declare module.exports: $Exports<'openseadragon/build/openseadragon/openseadragon'>;
}
declare module 'openseadragon/build/openseadragon/openseadragon.min.js' {
  declare module.exports: $Exports<'openseadragon/build/openseadragon/openseadragon.min'>;
}
