// flow-typed signature: 7f7edbfc8562ead6c476c65c7f01a6e4
// flow-typed version: <<STUB>>/prismic-dom_v2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prismic-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prismic-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prismic-dom/dist/prismic-dom' {
  declare module.exports: any;
}

declare module 'prismic-dom/dist/prismic-dom.min' {
  declare module.exports: any;
}

declare module 'prismic-dom/src/index' {
  declare module.exports: any;
}

declare module 'prismic-dom/src/richtext' {
  declare module.exports: any;
}

declare module 'prismic-dom/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prismic-dom/dist/prismic-dom.js' {
  declare module.exports: $Exports<'prismic-dom/dist/prismic-dom'>;
}
declare module 'prismic-dom/dist/prismic-dom.min.js' {
  declare module.exports: $Exports<'prismic-dom/dist/prismic-dom.min'>;
}
declare module 'prismic-dom/src/index.js' {
  declare module.exports: $Exports<'prismic-dom/src/index'>;
}
declare module 'prismic-dom/src/richtext.js' {
  declare module.exports: $Exports<'prismic-dom/src/richtext'>;
}
declare module 'prismic-dom/webpack.config.js' {
  declare module.exports: $Exports<'prismic-dom/webpack.config'>;
}
