// flow-typed signature: 9546d9efaace5f737a11034a571c5beb
// flow-typed version: <<STUB>>/prismic-reactjs_v1.1.2/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prismic-reactjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prismic-reactjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prismic-reactjs/dist/prismic-reactjs' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/dist/prismic-reactjs.min' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/src/Component' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/src/embeds' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/src' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/src/richtext' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/test/richtext' {
  declare module.exports: any;
}

declare module 'prismic-reactjs/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prismic-reactjs/dist/prismic-reactjs.js' {
  declare module.exports: $Exports<'prismic-reactjs/dist/prismic-reactjs'>;
}
declare module 'prismic-reactjs/dist/prismic-reactjs.min.js' {
  declare module.exports: $Exports<'prismic-reactjs/dist/prismic-reactjs.min'>;
}
declare module 'prismic-reactjs/src/Component.js' {
  declare module.exports: $Exports<'prismic-reactjs/src/Component'>;
}
declare module 'prismic-reactjs/src/embeds.js' {
  declare module.exports: $Exports<'prismic-reactjs/src/embeds'>;
}
declare module 'prismic-reactjs/src/index' {
  declare module.exports: $Exports<'prismic-reactjs/src'>;
}
declare module 'prismic-reactjs/src/index.js' {
  declare module.exports: $Exports<'prismic-reactjs/src'>;
}
declare module 'prismic-reactjs/src/richtext.js' {
  declare module.exports: $Exports<'prismic-reactjs/src/richtext'>;
}
declare module 'prismic-reactjs/test/richtext.js' {
  declare module.exports: $Exports<'prismic-reactjs/test/richtext'>;
}
declare module 'prismic-reactjs/webpack.config.js' {
  declare module.exports: $Exports<'prismic-reactjs/webpack.config'>;
}
