// flow-typed signature: 6f152069a5be11fe5a7441aaeb78e7d0
// flow-typed version: <<STUB>>/prismic-javascript_v1.5/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prismic-javascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prismic-javascript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prismic-javascript/dist/prismic-javascript' {
  declare module.exports: any;
}

declare module 'prismic-javascript/dist/prismic-javascript.min' {
  declare module.exports: any;
}

declare module 'prismic-javascript/docs/assets/js/main' {
  declare module.exports: any;
}

declare module 'prismic-javascript/docs/assets/js/search' {
  declare module.exports: any;
}

declare module 'prismic-javascript/test/api' {
  declare module.exports: any;
}

declare module 'prismic-javascript/test/cache' {
  declare module.exports: any;
}

declare module 'prismic-javascript/test/predicates' {
  declare module.exports: any;
}

declare module 'prismic-javascript/test/prismic' {
  declare module.exports: any;
}

declare module 'prismic-javascript/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prismic-javascript/dist/prismic-javascript.js' {
  declare module.exports: $Exports<'prismic-javascript/dist/prismic-javascript'>;
}
declare module 'prismic-javascript/dist/prismic-javascript.min.js' {
  declare module.exports: $Exports<'prismic-javascript/dist/prismic-javascript.min'>;
}
declare module 'prismic-javascript/docs/assets/js/main.js' {
  declare module.exports: $Exports<'prismic-javascript/docs/assets/js/main'>;
}
declare module 'prismic-javascript/docs/assets/js/search.js' {
  declare module.exports: $Exports<'prismic-javascript/docs/assets/js/search'>;
}
declare module 'prismic-javascript/test/api.js' {
  declare module.exports: $Exports<'prismic-javascript/test/api'>;
}
declare module 'prismic-javascript/test/cache.js' {
  declare module.exports: $Exports<'prismic-javascript/test/cache'>;
}
declare module 'prismic-javascript/test/predicates.js' {
  declare module.exports: $Exports<'prismic-javascript/test/predicates'>;
}
declare module 'prismic-javascript/test/prismic.js' {
  declare module.exports: $Exports<'prismic-javascript/test/prismic'>;
}
declare module 'prismic-javascript/webpack.config.js' {
  declare module.exports: $Exports<'prismic-javascript/webpack.config'>;
}
