// flow-typed signature: c581dba87e8857fc5ca98c45ca49db8f
// flow-typed version: <<STUB>>/raven-js_v3.x.x/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raven-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raven-js' {
  declare module.exports: any;
}
