// flow-typed signature: 4e17d8825ef9086a145b017242a9beaa
// flow-typed version: <<STUB>>/styled-components_v4.1.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}
