// flow-typed signature: d743a465e1e49aa27cb72c4e848b8b04
// flow-typed version: <<STUB>>/url-template_v2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-template' {
  declare module.exports: any;
}
