- label: 'get started'
  commands:
    bash .buildkite/scripts/run-e2e-on-pull-requests.sh

  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
