- label: "placeholder"
  command: echo "(this is a placeholder for e2es on PRs, nothing to see here)"

  agents:
    queue: nano

- wait

- input: "Do you want to run end-to-end tests on this pull request?"
  key: "ask-user-if-should-run-e2es"
  fields:
    - select: "Run e2es?"
      key: "should-run-e2es"
      required: false
      options:
        - label: "Yes, run e2e tests now"
          value: "yes"
        - label: "Not now, maybe later"
          value: "maybe-later"
        - label: "No, not needed for this PR"
          value: "no"

- command: "buildkite-agent meta-data get should-run-e2es"
  depends_on: "ask-user-if-should-run-e2es"

  agents:
    queue: nano
