- label: 'Deploy to e2e'
  commands: |
    ENV_TAG=content-env.e2e \
      LATEST_TAG=wc-dot-org-build-plus-test-content-build-11582 \
        .buildkite/scripts/update_ecr_image_tag.sh \
        uk.ac.wellcome/buildkite

    ENV_TAG=catalogue-env.e2e \
      LATEST_TAG=wc-dot-org-build-plus-test-catalogue-build-11582 \
        .buildkite/scripts/update_ecr_image_tag.sh \
        uk.ac.wellcome/buildkite

    ENV_TAG=identity-env.e2e \
      LATEST_TAG=wc-dot-org-build-plus-test-identity-build-11582 \
        .buildkite/scripts/update_ecr_image_tag.sh \
        uk.ac.wellcome/buildkite

    CLUSTER="experience-frontend-e2e" .buildkite/scripts/deploy_ecs_services.sh \
      "content-17092020-e2e" \
      "catalogue-17092020-e2e" \
      "identity-18012021-e2e"

  concurrency: 1
  concurrency_group: "dotorg-e2e-on-pull-requests"

  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
