steps:
  - label: "e2e test:desktop [$BUILDKITE_GITHUB_DEPLOYMENT_ENVIRONMENT]"
    plugins:
      - docker-compose#v3.5.0:
          run: e2e
          env:
            - PLAYWRIGHT_BASE_URL=$PLAYWRIGHT_BASE_URL
            - USE_STAGE_APIS=$USE_STAGE_APIS
          command: ["yarn", "test"]
    retry:
      automatic: true

  - label: "e2e test:mobile [$BUILDKITE_GITHUB_DEPLOYMENT_ENVIRONMENT]"
    plugins:
      - docker-compose#v3.5.0:
          run: e2e
          env:
            - PLAYWRIGHT_BASE_URL=$PLAYWRIGHT_BASE_URL
            - USE_STAGE_APIS=$USE_STAGE_APIS
          command: ["yarn", "test:mobile"]
    retry:
      automatic: true
