steps:
  - label: "build e2e test image"
    command: ./playwright/get_playwright_image.sh
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::130871440101:role/experience-ci"
      - ecr#v2.1.1:
          login: true

  - wait

  - label: "Check URLs"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::130871440101:role/experience-ci"
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: e2e
          env:
            - BASE_URL=$PLAYWRIGHT_BASE_URL
          volumes:
            - "./.buildkite/urls:/usr/src/app/webapp/playwright/urls"
          command: ["bash", "check_urls.sh"]
    retry:
      automatic: true

  - label: "e2e {{ matrix }} [$DEPLOYMENT_ENVIRONMENT]"

    matrix:
      - "test:desktop"
      - "test:mobile"

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::130871440101:role/experience-ci"
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: e2e
          env:
            - CI=true
            - PLAYWRIGHT_BASE_URL=$PLAYWRIGHT_BASE_URL
            - USE_STAGE_APIS=$USE_STAGE_APIS
          command: ["yarn", "{{ matrix }}"]
    agents:
      queue: scala  # High parallelism for expensive tests
    retry:
      automatic: true
