- label: ':docker: build common'
  key: 'build_common'
  agents:
    queue: test-upgrade
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build:
          - common
        image-repository: 130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- label: ':docker: build catalogue'
  agents:
    queue: test-upgrade
  key: 'build_catalogue'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build:
          - catalogue
        image-repository: 130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- label: ':docker: build content'
  agents:
    queue: test-upgrade
  key: 'build_content'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build:
          - content
        image-repository: 130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- label: ':docker: build edge_lambdas'
  key: 'build_edge_lambdas'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build:
          - edge_lambdas
        image-repository: 130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- label: ':docker: build identity'
  key: 'build_identity'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build:
          - identity
        image-repository: 130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- label: ':docker: build dash'
  branches: 'main'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build:
          - dash
        image-repository: 130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- label: 'diff prismic model'
  branches: 'main'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: prismic_model
        env:
          - CI
        command: ['yarn', 'diffCustomTypes']

- label: 'test common'
  depends_on: 'build_common'
  agents:
    queue: test-upgrade
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: common
        command: ['yarn', 'test']

- label: 'test catalogue'
  depends_on: 'build_catalogue'
  agents:
    queue: test-upgrade
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: catalogue
        command: ['yarn', 'test']

- label: 'test content'
  agents:
    queue: test-upgrade
  depends_on: 'build_content'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: content
        command: ['yarn', 'test']

- label: 'test identity'
  depends_on: 'build_identity'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: identity
        command: ['yarn', 'test']

- label: 'test edge_lambdas'
  depends_on: 'build_edge_lambdas'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: edge_lambdas
        command: ['yarn', 'test']

# This step kicks of the "end-to-end on pull requests" flow.
#
# It doesn't run on main, because we run e2es on main by deploying
# into our stage/prod environments instead.
- label: "check if we need to run e2es"
  command: .buildkite/e2e_on_pull_requests/check_if_we_need_to_ask.sh
  if: build.branch != "main"

  agents:
    queue: nano

- wait

- label: 'deploy catalogue'
  branches: 'main'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - catalogue:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/catalogue_webapp:ref.${BUILDKITE_COMMIT}
          - catalogue:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/catalogue_webapp:latest

- label: 'deploy content'
  branches: 'main'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - content:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/content_webapp:ref.${BUILDKITE_COMMIT}
          - content:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/content_webapp:latest

- label: 'deploy identity'
  branches: 'main'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - identity:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/identity_webapp:ref.${BUILDKITE_COMMIT}
          - identity:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/identity_webapp:latest

- label: 'deploy dash'
  branches: 'main'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: dash
        command: ['yarn', 'deploy']
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: 'deploy edge_lambdas'
  branches: 'main'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: edge_lambdas
        command: ['yarn', 'deploy']
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: 'deploy updown'
  branches: 'main'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: updown
        command: ['yarn', 'checks']
        env:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN

- label: 'deploy assets'
  branches: 'main'
  commands: ./assets/deploy_assets.sh
  agents:
    queue: nano

- wait

- label: 'Trigger stage deployment'
  branches: 'main'
  plugins:
    - wellcomecollection/github-deployments#v0.3.0:
        assume_role: 'arn:aws:iam::130871440101:role/experience-ci'
        environment: stage
        ref: '${BUILDKITE_COMMIT}'
  agents:
    queue: nano
