- label: 'Deploy to e2e'
  commands: |
    ENV_TAG=content-env.e2e \
      LATEST_TAG=wc-dot-org-build-plus-test-content-build-11716 \
        .buildkite/scripts/update_ecr_image_tag.sh \
        uk.ac.wellcome/buildkite

    ENV_TAG=catalogue-env.e2e \
      LATEST_TAG=wc-dot-org-build-plus-test-catalogue-build-11716 \
        .buildkite/scripts/update_ecr_image_tag.sh \
        uk.ac.wellcome/buildkite

    ENV_TAG=identity-env.e2e \
      LATEST_TAG=wc-dot-org-build-plus-test-identity-build-11716 \
        .buildkite/scripts/update_ecr_image_tag.sh \
        uk.ac.wellcome/buildkite

    CLUSTER="experience-frontend-e2e" .buildkite/scripts/deploy_ecs_services.sh \
      "content-17092020-e2e" \
      "catalogue-17092020-e2e" \
      "identity-18012021-e2e"

  # This implements a lock around the pipeline, which means only one PR
  # can be running e2e tests at a time.
  #
  # See the comment about "concurrency gates" in the deployment pipeline.
  concurrency_group: "dotorg-e2e-on-pull-requests-gate"
  concurrency: 1
  key: deploy-to-e2e-environment

  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'

  agents:
    queue: nano

  concurrency_group: "front-end-deployment-${BUILDKITE_GITHUB_DEPLOYMENT_ENVIRONMENT}-gate"
  concurrency: 1

- label: "Trigger e2e tests"
  command: ".buildkite/scripts/trigger-e2e-on-pull-request.sh"

  depends_on: deploy-to-e2e-environment

  agents:
    queue: nano

- wait

- label: "complete e2e tests on PR"
  command: echo "End of concurrency gate <--"

  concurrency_group: "dotorg-e2e-on-pull-requests-gate"
  concurrency: 1
