steps:
  - label: "e2e test:desktop [$DEPLOYMENT_ENVIRONMENT]"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::130871440101:role/experience-ci"
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: e2e
          env:
            - CI=true
            - PLAYWRIGHT_BASE_URL=https://www-stage.wellcomecollection.org
          command: ["yarn", "test"]
    agents:
      queue: scala # High parallelism for expensive tests
    retry:
      automatic: true

  - label: "e2e test:mobile [$DEPLOYMENT_ENVIRONMENT]"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::130871440101:role/experience-ci"
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: e2e
          env:
            - CI=true
            - PLAYWRIGHT_BASE_URL=https://www-stage.wellcomecollection.org
          command: ["yarn", "test:mobile"]
    agents:
      queue: scala # High parallelism for expensive tests
    retry:
      automatic: true
