- label: "placeholder"
  command: echo "(this is a placeholder for e2es on PRs, nothing to see here)"

  agents:
    queue: nano

- label: "check if we need to run e2es"
  command: .buildkite/e2e_on_pull_requests/check_if_we_need_to_ask.sh
