- label: ":docker: Build identity"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build-parallel: true
        build:
          - identity
        image-repository: 130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- label: ":docker: Build identity-admin"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build-parallel: true
        build:
          - identity-admin
        image-repository: 130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- wait

- label: "deploy identity (ecr image)"
  branches: "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - identity:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/identity_webapp:ref.${BUILDKITE_COMMIT}
          - identity:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/identity_webapp:latest

- label: "deploy identity admin (ecr image)"
  branches: "master"
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: "arn:aws:iam::130871440101:role/experience-ci"
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        push:
          - identity:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/identity-admin_webapp:ref.${BUILDKITE_COMMIT}
          - identity:130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/identity-admin_webapp:latest

- wait

- label: "deploy to stage"
  branches: "master"
  concurrency: 1
  concurrency_group: "experience-identity-deploy"
  plugins:
    - docker#v3.5.0:
        image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.6.16
        workdir: /repo
        mount-ssh-agent: true
        command: [
            "--confirm",
            "--project-id", "identity",
            "release-deploy",
            "--from-label", "ref.$BUILDKITE_COMMIT",
            "--environment-id", "stage",
            "--description", $BUILDKITE_BUILD_URL,
            "--confirmation-wait-for", 3540] # Session times out at 3600s / 1 hour


