- label: ':docker: build catalogue'
  key: 'build_catalogue'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        build:
          - catalogue
        image-repository: 130871440101.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/buildkite

- label: 'test catalogue'
  depends_on: 'build_catalogue'
  plugins:
    - wellcomecollection/aws-assume-role#v0.2.2:
        role: 'arn:aws:iam::130871440101:role/experience-ci'
    - ecr#v2.1.1:
        login: true
    - docker-compose#v3.5.0:
        run: catalogue
        command: ['yarn', 'test']
