// flow-typed signature: dc7b88efd6e70c7628d57a1f3403c3c4
// flow-typed version: <<STUB>>/@weco/common_v../../common/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@weco/common'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@weco/common' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@weco/common/data/series' {
  declare module.exports: any;
}

declare module '@weco/common/icons/arrow' {
  declare module.exports: any;
}

declare module '@weco/common/icons/check' {
  declare module.exports: any;
}

declare module '@weco/common/icons/chevron' {
  declare module.exports: any;
}

declare module '@weco/common/icons/clear' {
  declare module.exports: any;
}

declare module '@weco/common/icons/clock' {
  declare module.exports: any;
}

declare module '@weco/common/icons/cross' {
  declare module.exports: any;
}

declare module '@weco/common/icons/download' {
  declare module.exports: any;
}

declare module '@weco/common/icons/gallery' {
  declare module.exports: any;
}

declare module '@weco/common/icons/hearing_loop' {
  declare module.exports: any;
}

declare module '@weco/common/icons/image' {
  declare module.exports: any;
}

declare module '@weco/common/icons/index' {
  declare module.exports: any;
}

declare module '@weco/common/icons/information' {
  declare module.exports: any;
}

declare module '@weco/common/icons/licenses' {
  declare module.exports: any;
}

declare module '@weco/common/icons/play' {
  declare module.exports: any;
}

declare module '@weco/common/icons/plus' {
  declare module.exports: any;
}

declare module '@weco/common/icons/search' {
  declare module.exports: any;
}

declare module '@weco/common/icons/under_construction' {
  declare module.exports: any;
}

declare module '@weco/common/icons/volume' {
  declare module.exports: any;
}

declare module '@weco/common/icons/wellcome_collection_black' {
  declare module.exports: any;
}

declare module '@weco/common/icons/zoom-in' {
  declare module.exports: any;
}

declare module '@weco/common/icons/zoom-out' {
  declare module.exports: any;
}

declare module '@weco/common/model/content-type' {
  declare module.exports: any;
}

declare module '@weco/common/model/license' {
  declare module.exports: any;
}

declare module '@weco/common/model/link' {
  declare module.exports: any;
}

declare module '@weco/common/model/meta-unit' {
  declare module.exports: any;
}

declare module '@weco/common/model/weight' {
  declare module.exports: any;
}

declare module '@weco/common/services/prismic/api' {
  declare module.exports: any;
}

declare module '@weco/common/services/prismic/article' {
  declare module.exports: any;
}

declare module '@weco/common/services/prismic/types' {
  declare module.exports: any;
}

declare module '@weco/common/utils/classnames' {
  declare module.exports: any;
}

declare module '@weco/common/utils/convert-image-uri' {
  declare module.exports: any;
}

declare module '@weco/common/utils/format-date' {
  declare module.exports: any;
}

declare module '@weco/common/utils/get-icon-for-content-type' {
  declare module.exports: any;
}

declare module '@weco/common/utils/get-license-info' {
  declare module.exports: any;
}

declare module '@weco/common/utils/get-series-title' {
  declare module.exports: any;
}

declare module '@weco/common/utils/image-sizes' {
  declare module.exports: any;
}

declare module '@weco/common/utils/striptags' {
  declare module.exports: any;
}

declare module '@weco/common/utils/tracking' {
  declare module.exports: any;
}

declare module '@weco/common/utils/truncate' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/BackToTop/BackToTop.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/BackToTop/BackToTop' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Buttons/ButtonButton/ButtonButton.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Buttons/ButtonButton/ButtonButton' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/CaptionedImage/CaptionedImage.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/CaptionedImage/CaptionedImage' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/ChapterIndicator/ChapterIndicator.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/ChapterIndicator/ChapterIndicator' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/CopyUrl/CopyUrl.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/CopyUrl/CopyUrl' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/DefaultPageLayout/DefaultPageLayout.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/DefaultPageLayout/DefaultPageLayout' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Divider/Divider.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Divider/Divider' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Header/Header' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Header/HeadJs' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/HTMLInput/HTMLInput.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/HTMLInput/HTMLInput' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Icon/Icon.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Icon/Icon' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Image/Image.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Image/Image' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/ImageViewer/ImageViewer.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/ImageViewer/ImageViewer' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/ImageViewer/ImageViewer2' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Index/index.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Index/index' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/InfoBanner/InfoBanner' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/layout/layout.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/layout/preview-no-container' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/layout/preview' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/License/License.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/License/License' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/MetaUnit/MetaUnit.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/MetaUnit/MetaUnit' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/MoreInfoLink/MoreInfoLink.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/MoreInfoLink/MoreInfoLink' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/PageDescription/PageDescription.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/PageDescription/PageDescription' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Pagination/Pagination.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Pagination/Pagination' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Promo/Promo.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Promo/Promo' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/ScrollToInfo/ScrollToInfo.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/ScrollToInfo/ScrollToInfo' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/SearchBox/SearchBox.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/SearchBox/SearchBox' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/StaticWorksContent/StaticWorksContent.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/StaticWorksContent/StaticWorksContent' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Tags/Tags.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Tags/Tags' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Tasl/Tasl.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/Tasl/Tasl' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/WorkDrawer/WorkDrawer.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/WorkDrawer/WorkDrawer' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/WorkMedia/WorkMedia.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/WorkMedia/WorkMedia' {
  declare module.exports: any;
}

declare module '@weco/common/views/components/WorkMedia/WorkMedia2' {
  declare module.exports: any;
}

declare module '@weco/common/views/global/icons/icons.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/global/icons/icons' {
  declare module.exports: any;
}

declare module '@weco/common/views/global/palette/palette.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/global/palette/palette' {
  declare module.exports: any;
}

declare module '@weco/common/views/global/typography/typography.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/global/typography/typography' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/aligning/aligning.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/aligning/aligning' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/basic/basic.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/basic/basic' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/breakout/breakout.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/breakout/breakout' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/container_queries/container_queries.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/container_queries/container_queries' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/dividers/dividers.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/dividers/dividers' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/nesting/nesting.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/nesting/nesting' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/sizing/sizing.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/grid/sizing/sizing' {
  declare module.exports: any;
}

declare module '@weco/common/views/templates/article/article.config' {
  declare module.exports: any;
}

declare module '@weco/common/views/templates/article/article' {
  declare module.exports: any;
}

// Filename aliases
declare module '@weco/common/data/series.js' {
  declare module.exports: $Exports<'@weco/common/data/series'>;
}
declare module '@weco/common/icons/arrow.js' {
  declare module.exports: $Exports<'@weco/common/icons/arrow'>;
}
declare module '@weco/common/icons/check.js' {
  declare module.exports: $Exports<'@weco/common/icons/check'>;
}
declare module '@weco/common/icons/chevron.js' {
  declare module.exports: $Exports<'@weco/common/icons/chevron'>;
}
declare module '@weco/common/icons/clear.js' {
  declare module.exports: $Exports<'@weco/common/icons/clear'>;
}
declare module '@weco/common/icons/clock.js' {
  declare module.exports: $Exports<'@weco/common/icons/clock'>;
}
declare module '@weco/common/icons/cross.js' {
  declare module.exports: $Exports<'@weco/common/icons/cross'>;
}
declare module '@weco/common/icons/download.js' {
  declare module.exports: $Exports<'@weco/common/icons/download'>;
}
declare module '@weco/common/icons/gallery.js' {
  declare module.exports: $Exports<'@weco/common/icons/gallery'>;
}
declare module '@weco/common/icons/hearing_loop.js' {
  declare module.exports: $Exports<'@weco/common/icons/hearing_loop'>;
}
declare module '@weco/common/icons/image.js' {
  declare module.exports: $Exports<'@weco/common/icons/image'>;
}
declare module '@weco/common/icons/index.js' {
  declare module.exports: $Exports<'@weco/common/icons/index'>;
}
declare module '@weco/common/icons/information.js' {
  declare module.exports: $Exports<'@weco/common/icons/information'>;
}
declare module '@weco/common/icons/licenses.js' {
  declare module.exports: $Exports<'@weco/common/icons/licenses'>;
}
declare module '@weco/common/icons/play.js' {
  declare module.exports: $Exports<'@weco/common/icons/play'>;
}
declare module '@weco/common/icons/plus.js' {
  declare module.exports: $Exports<'@weco/common/icons/plus'>;
}
declare module '@weco/common/icons/search.js' {
  declare module.exports: $Exports<'@weco/common/icons/search'>;
}
declare module '@weco/common/icons/under_construction.js' {
  declare module.exports: $Exports<'@weco/common/icons/under_construction'>;
}
declare module '@weco/common/icons/volume.js' {
  declare module.exports: $Exports<'@weco/common/icons/volume'>;
}
declare module '@weco/common/icons/wellcome_collection_black.js' {
  declare module.exports: $Exports<'@weco/common/icons/wellcome_collection_black'>;
}
declare module '@weco/common/icons/zoom-in.js' {
  declare module.exports: $Exports<'@weco/common/icons/zoom-in'>;
}
declare module '@weco/common/icons/zoom-out.js' {
  declare module.exports: $Exports<'@weco/common/icons/zoom-out'>;
}
declare module '@weco/common/model/content-type.js' {
  declare module.exports: $Exports<'@weco/common/model/content-type'>;
}
declare module '@weco/common/model/license.js' {
  declare module.exports: $Exports<'@weco/common/model/license'>;
}
declare module '@weco/common/model/link.js' {
  declare module.exports: $Exports<'@weco/common/model/link'>;
}
declare module '@weco/common/model/meta-unit.js' {
  declare module.exports: $Exports<'@weco/common/model/meta-unit'>;
}
declare module '@weco/common/model/weight.js' {
  declare module.exports: $Exports<'@weco/common/model/weight'>;
}
declare module '@weco/common/services/prismic/api.js' {
  declare module.exports: $Exports<'@weco/common/services/prismic/api'>;
}
declare module '@weco/common/services/prismic/article.js' {
  declare module.exports: $Exports<'@weco/common/services/prismic/article'>;
}
declare module '@weco/common/services/prismic/types.js' {
  declare module.exports: $Exports<'@weco/common/services/prismic/types'>;
}
declare module '@weco/common/utils/classnames.js' {
  declare module.exports: $Exports<'@weco/common/utils/classnames'>;
}
declare module '@weco/common/utils/convert-image-uri.js' {
  declare module.exports: $Exports<'@weco/common/utils/convert-image-uri'>;
}
declare module '@weco/common/utils/format-date.js' {
  declare module.exports: $Exports<'@weco/common/utils/format-date'>;
}
declare module '@weco/common/utils/get-icon-for-content-type.js' {
  declare module.exports: $Exports<'@weco/common/utils/get-icon-for-content-type'>;
}
declare module '@weco/common/utils/get-license-info.js' {
  declare module.exports: $Exports<'@weco/common/utils/get-license-info'>;
}
declare module '@weco/common/utils/get-series-title.js' {
  declare module.exports: $Exports<'@weco/common/utils/get-series-title'>;
}
declare module '@weco/common/utils/image-sizes.js' {
  declare module.exports: $Exports<'@weco/common/utils/image-sizes'>;
}
declare module '@weco/common/utils/striptags.js' {
  declare module.exports: $Exports<'@weco/common/utils/striptags'>;
}
declare module '@weco/common/utils/tracking.js' {
  declare module.exports: $Exports<'@weco/common/utils/tracking'>;
}
declare module '@weco/common/utils/truncate.js' {
  declare module.exports: $Exports<'@weco/common/utils/truncate'>;
}
declare module '@weco/common/views/components/BackToTop/BackToTop.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/BackToTop/BackToTop.config'>;
}
declare module '@weco/common/views/components/BackToTop/BackToTop.js' {
  declare module.exports: $Exports<'@weco/common/views/components/BackToTop/BackToTop'>;
}
declare module '@weco/common/views/components/Buttons/ButtonButton/ButtonButton.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Buttons/ButtonButton/ButtonButton.config'>;
}
declare module '@weco/common/views/components/Buttons/ButtonButton/ButtonButton.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Buttons/ButtonButton/ButtonButton'>;
}
declare module '@weco/common/views/components/CaptionedImage/CaptionedImage.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/CaptionedImage/CaptionedImage.config'>;
}
declare module '@weco/common/views/components/CaptionedImage/CaptionedImage.js' {
  declare module.exports: $Exports<'@weco/common/views/components/CaptionedImage/CaptionedImage'>;
}
declare module '@weco/common/views/components/ChapterIndicator/ChapterIndicator.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/ChapterIndicator/ChapterIndicator.config'>;
}
declare module '@weco/common/views/components/ChapterIndicator/ChapterIndicator.js' {
  declare module.exports: $Exports<'@weco/common/views/components/ChapterIndicator/ChapterIndicator'>;
}
declare module '@weco/common/views/components/CopyUrl/CopyUrl.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/CopyUrl/CopyUrl.config'>;
}
declare module '@weco/common/views/components/CopyUrl/CopyUrl.js' {
  declare module.exports: $Exports<'@weco/common/views/components/CopyUrl/CopyUrl'>;
}
declare module '@weco/common/views/components/DefaultPageLayout/DefaultPageLayout.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/DefaultPageLayout/DefaultPageLayout.config'>;
}
declare module '@weco/common/views/components/DefaultPageLayout/DefaultPageLayout.js' {
  declare module.exports: $Exports<'@weco/common/views/components/DefaultPageLayout/DefaultPageLayout'>;
}
declare module '@weco/common/views/components/Divider/Divider.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Divider/Divider.config'>;
}
declare module '@weco/common/views/components/Divider/Divider.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Divider/Divider'>;
}
declare module '@weco/common/views/components/Header/Header.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Header/Header'>;
}
declare module '@weco/common/views/components/Header/HeadJs.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Header/HeadJs'>;
}
declare module '@weco/common/views/components/HTMLInput/HTMLInput.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/HTMLInput/HTMLInput.config'>;
}
declare module '@weco/common/views/components/HTMLInput/HTMLInput.js' {
  declare module.exports: $Exports<'@weco/common/views/components/HTMLInput/HTMLInput'>;
}
declare module '@weco/common/views/components/Icon/Icon.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Icon/Icon.config'>;
}
declare module '@weco/common/views/components/Icon/Icon.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Icon/Icon'>;
}
declare module '@weco/common/views/components/Image/Image.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Image/Image.config'>;
}
declare module '@weco/common/views/components/Image/Image.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Image/Image'>;
}
declare module '@weco/common/views/components/ImageViewer/ImageViewer.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/ImageViewer/ImageViewer.config'>;
}
declare module '@weco/common/views/components/ImageViewer/ImageViewer.js' {
  declare module.exports: $Exports<'@weco/common/views/components/ImageViewer/ImageViewer'>;
}
declare module '@weco/common/views/components/ImageViewer/ImageViewer2.js' {
  declare module.exports: $Exports<'@weco/common/views/components/ImageViewer/ImageViewer2'>;
}
declare module '@weco/common/views/components/Index/index.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Index/index.config'>;
}
declare module '@weco/common/views/components/Index/index.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Index/index'>;
}
declare module '@weco/common/views/components/InfoBanner/InfoBanner.js' {
  declare module.exports: $Exports<'@weco/common/views/components/InfoBanner/InfoBanner'>;
}
declare module '@weco/common/views/components/layout/layout.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/layout/layout.config'>;
}
declare module '@weco/common/views/components/layout/preview-no-container.js' {
  declare module.exports: $Exports<'@weco/common/views/components/layout/preview-no-container'>;
}
declare module '@weco/common/views/components/layout/preview.js' {
  declare module.exports: $Exports<'@weco/common/views/components/layout/preview'>;
}
declare module '@weco/common/views/components/License/License.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/License/License.config'>;
}
declare module '@weco/common/views/components/License/License.js' {
  declare module.exports: $Exports<'@weco/common/views/components/License/License'>;
}
declare module '@weco/common/views/components/MetaUnit/MetaUnit.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/MetaUnit/MetaUnit.config'>;
}
declare module '@weco/common/views/components/MetaUnit/MetaUnit.js' {
  declare module.exports: $Exports<'@weco/common/views/components/MetaUnit/MetaUnit'>;
}
declare module '@weco/common/views/components/MoreInfoLink/MoreInfoLink.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/MoreInfoLink/MoreInfoLink.config'>;
}
declare module '@weco/common/views/components/MoreInfoLink/MoreInfoLink.js' {
  declare module.exports: $Exports<'@weco/common/views/components/MoreInfoLink/MoreInfoLink'>;
}
declare module '@weco/common/views/components/PageDescription/PageDescription.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/PageDescription/PageDescription.config'>;
}
declare module '@weco/common/views/components/PageDescription/PageDescription.js' {
  declare module.exports: $Exports<'@weco/common/views/components/PageDescription/PageDescription'>;
}
declare module '@weco/common/views/components/Pagination/Pagination.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Pagination/Pagination.config'>;
}
declare module '@weco/common/views/components/Pagination/Pagination.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Pagination/Pagination'>;
}
declare module '@weco/common/views/components/Promo/Promo.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Promo/Promo.config'>;
}
declare module '@weco/common/views/components/Promo/Promo.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Promo/Promo'>;
}
declare module '@weco/common/views/components/ScrollToInfo/ScrollToInfo.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/ScrollToInfo/ScrollToInfo.config'>;
}
declare module '@weco/common/views/components/ScrollToInfo/ScrollToInfo.js' {
  declare module.exports: $Exports<'@weco/common/views/components/ScrollToInfo/ScrollToInfo'>;
}
declare module '@weco/common/views/components/SearchBox/SearchBox.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/SearchBox/SearchBox.config'>;
}
declare module '@weco/common/views/components/SearchBox/SearchBox.js' {
  declare module.exports: $Exports<'@weco/common/views/components/SearchBox/SearchBox'>;
}
declare module '@weco/common/views/components/StaticWorksContent/StaticWorksContent.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/StaticWorksContent/StaticWorksContent.config'>;
}
declare module '@weco/common/views/components/StaticWorksContent/StaticWorksContent.js' {
  declare module.exports: $Exports<'@weco/common/views/components/StaticWorksContent/StaticWorksContent'>;
}
declare module '@weco/common/views/components/Tags/Tags.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Tags/Tags.config'>;
}
declare module '@weco/common/views/components/Tags/Tags.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Tags/Tags'>;
}
declare module '@weco/common/views/components/Tasl/Tasl.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Tasl/Tasl.config'>;
}
declare module '@weco/common/views/components/Tasl/Tasl.js' {
  declare module.exports: $Exports<'@weco/common/views/components/Tasl/Tasl'>;
}
declare module '@weco/common/views/components/WorkDrawer/WorkDrawer.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/WorkDrawer/WorkDrawer.config'>;
}
declare module '@weco/common/views/components/WorkDrawer/WorkDrawer.js' {
  declare module.exports: $Exports<'@weco/common/views/components/WorkDrawer/WorkDrawer'>;
}
declare module '@weco/common/views/components/WorkMedia/WorkMedia.config.js' {
  declare module.exports: $Exports<'@weco/common/views/components/WorkMedia/WorkMedia.config'>;
}
declare module '@weco/common/views/components/WorkMedia/WorkMedia.js' {
  declare module.exports: $Exports<'@weco/common/views/components/WorkMedia/WorkMedia'>;
}
declare module '@weco/common/views/components/WorkMedia/WorkMedia2.js' {
  declare module.exports: $Exports<'@weco/common/views/components/WorkMedia/WorkMedia2'>;
}
declare module '@weco/common/views/global/icons/icons.config.js' {
  declare module.exports: $Exports<'@weco/common/views/global/icons/icons.config'>;
}
declare module '@weco/common/views/global/icons/icons.js' {
  declare module.exports: $Exports<'@weco/common/views/global/icons/icons'>;
}
declare module '@weco/common/views/global/palette/palette.config.js' {
  declare module.exports: $Exports<'@weco/common/views/global/palette/palette.config'>;
}
declare module '@weco/common/views/global/palette/palette.js' {
  declare module.exports: $Exports<'@weco/common/views/global/palette/palette'>;
}
declare module '@weco/common/views/global/typography/typography.config.js' {
  declare module.exports: $Exports<'@weco/common/views/global/typography/typography.config'>;
}
declare module '@weco/common/views/global/typography/typography.js' {
  declare module.exports: $Exports<'@weco/common/views/global/typography/typography'>;
}
declare module '@weco/common/views/grid/aligning/aligning.config.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/aligning/aligning.config'>;
}
declare module '@weco/common/views/grid/aligning/aligning.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/aligning/aligning'>;
}
declare module '@weco/common/views/grid/basic/basic.config.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/basic/basic.config'>;
}
declare module '@weco/common/views/grid/basic/basic.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/basic/basic'>;
}
declare module '@weco/common/views/grid/breakout/breakout.config.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/breakout/breakout.config'>;
}
declare module '@weco/common/views/grid/breakout/breakout.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/breakout/breakout'>;
}
declare module '@weco/common/views/grid/container_queries/container_queries.config.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/container_queries/container_queries.config'>;
}
declare module '@weco/common/views/grid/container_queries/container_queries.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/container_queries/container_queries'>;
}
declare module '@weco/common/views/grid/dividers/dividers.config.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/dividers/dividers.config'>;
}
declare module '@weco/common/views/grid/dividers/dividers.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/dividers/dividers'>;
}
declare module '@weco/common/views/grid/nesting/nesting.config.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/nesting/nesting.config'>;
}
declare module '@weco/common/views/grid/nesting/nesting.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/nesting/nesting'>;
}
declare module '@weco/common/views/grid/sizing/sizing.config.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/sizing/sizing.config'>;
}
declare module '@weco/common/views/grid/sizing/sizing.js' {
  declare module.exports: $Exports<'@weco/common/views/grid/sizing/sizing'>;
}
declare module '@weco/common/views/templates/article/article.config.js' {
  declare module.exports: $Exports<'@weco/common/views/templates/article/article.config'>;
}
declare module '@weco/common/views/templates/article/article.js' {
  declare module.exports: $Exports<'@weco/common/views/templates/article/article'>;
}
