// flow-typed signature: d8ba0b3c3b56148298f3ec912b176652
// flow-typed version: <<STUB>>/@weco/next-plugin-transpile-modules_v^0.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@weco/next-plugin-transpile-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@weco/next-plugin-transpile-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@weco/next-plugin-transpile-modules/index' {
  declare module.exports: $Exports<'@weco/next-plugin-transpile-modules'>;
}
declare module '@weco/next-plugin-transpile-modules/index.js' {
  declare module.exports: $Exports<'@weco/next-plugin-transpile-modules'>;
}
