---
name: Bug report
about: Create a report to help us improve
labels: 'Bug+🐛'
projects: 'wellcomecollection/18'
---

## What
<!-- A clear and concise description of what the bug is. -->

## Where
<!-- a link, or a screenshot if relevant, as to where the bug is-->
