module.exports = {
  plugins: [
    {
      name: 'removeAttrs',
      params: {
        attrs: '.*:fill',
        preserveCurrentColor: true,
      },
    },
    { name: 'removeDoctype' },
    { name: 'removeXMLProcInst' },
    { name: 'removeComments' },
    { name: 'removeMetadata' },
    { name: 'removeXMLNS' },
    { name: 'removeXlink' },
    { name: 'removeEditorsNSData' },
    { name: 'cleanupAttrs' },
    { name: 'inlineStyles' },
    { name: 'minifyStyles' },
    { name: 'convertStyleToAttrs' },
    { name: 'cleanupIds' },
    { name: 'removeRasterImages' },
    { name: 'removeUselessDefs' },
    { name: 'cleanupNumericValues' },
    { name: 'cleanupListOfValues' },
    { name: 'convertColors' },
    { name: 'removeUnknownsAndDefaults' },
    { name: 'removeNonInheritableGroupAttrs' },
    { name: 'removeUselessStrokeAndFill' },
    { name: 'cleanupEnableBackground' },
    { name: 'removeHiddenElems' },
    { name: 'removeEmptyText' },
    { name: 'convertShapeToPath' },
    { name: 'collapseGroups' },
    { name: 'convertPathData' },
    { name: 'convertTransform' },
    { name: 'removeEmptyAttrs' },
    { name: 'removeEmptyContainers' },
    { name: 'mergePaths' },
    { name: 'removeUnusedNS' },
    { name: 'sortAttrs' },
    { name: 'removeTitle' },
    { name: 'removeDesc' },
    { name: 'removeDimensions' },
    { name: 'removeStyleElement' },
    { name: 'removeScriptElement' },
    { name: 'removeOffCanvasPaths' },
    { name: 'reusePaths' },
  ],
};
