function template({ componentName, jsx, exports, interfaces, props }, { tpl }) {
  const comment = `// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
  `;

  return tpl`
    ${comment}

    import { SVGProps } from 'react';
    ${interfaces}

    function ${componentName}(${props}) {
      return ${jsx};
    }

    ${exports}
  `;
}
module.exports = template;
