// flow-typed signature: 076031a8864a230b69c436835180d1bd
// flow-typed version: <<STUB>>/@segment/snippet_v4.x.x/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@segment/snippet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@segment/snippet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@segment/snippet/dist/max.template' {
  declare module.exports: any;
}

declare module '@segment/snippet/dist/min.template' {
  declare module.exports: any;
}

declare module '@segment/snippet/karma.conf.ci' {
  declare module.exports: any;
}

declare module '@segment/snippet/karma.conf' {
  declare module.exports: any;
}

declare module '@segment/snippet/lib' {
  declare module.exports: any;
}

declare module '@segment/snippet/scripts/build' {
  declare module.exports: any;
}

declare module '@segment/snippet/template/snippet' {
  declare module.exports: any;
}

// Filename aliases
declare module '@segment/snippet/dist/max.template.js' {
  declare module.exports: $Exports<'@segment/snippet/dist/max.template'>;
}
declare module '@segment/snippet/dist/min.template.js' {
  declare module.exports: $Exports<'@segment/snippet/dist/min.template'>;
}
declare module '@segment/snippet/karma.conf.ci.js' {
  declare module.exports: $Exports<'@segment/snippet/karma.conf.ci'>;
}
declare module '@segment/snippet/karma.conf.js' {
  declare module.exports: $Exports<'@segment/snippet/karma.conf'>;
}
declare module '@segment/snippet/lib/index' {
  declare module.exports: $Exports<'@segment/snippet/lib'>;
}
declare module '@segment/snippet/lib/index.js' {
  declare module.exports: $Exports<'@segment/snippet/lib'>;
}
declare module '@segment/snippet/scripts/build.js' {
  declare module.exports: $Exports<'@segment/snippet/scripts/build'>;
}
declare module '@segment/snippet/template/snippet.js' {
  declare module.exports: $Exports<'@segment/snippet/template/snippet'>;
}
