/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSchema {
  patronId: number;
  barcode: string;
  title: string;
  firstName: string;
  lastName: string;
  email: string;
  emailValidated: boolean;
  locked: boolean;
  creationDate: string;
  lastLogin: string;
  lastLoginIp: string;
  totalLogins: number;
}
