export const zoomInButton = 'css=button >> text="Zoom in"';
export const rotateButton = 'css=button >> text="Rotate"';
export const openseadragonCanvas = `.openseadragon-canvas`;
export const downloadsButton = `[aria-controls="itemDownloads"]`;
export const itemDownloadsModal = `#itemDownloads`;
export const smallImageDownload = `${itemDownloadsModal} li:nth-of-type(1) a`;
export const fullItemDownload = `${itemDownloadsModal} li:nth-of-type(3) a`;
export const workContributors = `[data-test-id="work-contributors"]`;
export const workDates = `[data-test-id="work-dates"]`;
export const fullscreenButton = 'css=button >> text="Full screen"';
export const searchWithinResultsHeader = `[data-test-id="results-header"]`;
export const mainViewer = `[data-test-id=main-viewer] > div`;
export const activeIndex = `[data-test-id=active-index]`;
export const searchWithinTextInput = `#searchWithin`;
