version: "3"
services:

  service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/home/node/app/src
      - ./lib:/home/node/app/lib
      - ./schemas:/home/node/app/schemas
      - ./package.json:/home/node/app/package.json
      - ./ecosystem.config.js:/home/node/app/ecosystem.config.js
    environment:
      - NODE_ENV=development
      - AUTH_METHOD=${AUTH_METHOD}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
      - SERVER_PORT=${SERVER_PORT:-3000}
      - API_BASE_URL=${API_BASE_URL}
      - API_KEY=${API_KEY}
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
