
FROM 770700576653.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/identity-node:12

WORKDIR /home/node/app

RUN npm install -g pm2 ts-node

COPY ./package.json /home/node/app/package.json

RUN yarn install --no-dev --no-interactive --frozen-lockfile

COPY ./schemas /home/node/app/schemas
COPY ./src /home/node/app/src
COPY ./ecosystem.config.js /home/node/app/ecosystem.config.js
COPY ./tsconfig.json /home/node/app/tsconfig.json
COPY ./tsconfig.frontend.json /home/node/app/tsconfig.frontend.json
COPY ./webpack.frontend.js /home/node/app/webpack.frontend.js
COPY ./generate-schemas.js /home/node/app/generate-schemas.js
COPY ./schemas /home/node/app/schemas

ENV SERVER_PORT=3000
ENV NODE_ENV=development

RUN yarn build

EXPOSE 3000
EXPOSE 9229

CMD ["yarn", "start"]
