// @flow
import type {Person} from '../model/person';
import * as people from '../data/people';

export const authorMap: { [key: string]: Person } = {
  'oops-i-wrote-a-britney-blog-post': people.russellDornan,
  'something-in-the-air': people.ruthGarde,
  'thunderbolts-and-lightning': people.ruthGarde,
  'eels-and-feels': people.ruthGarde,
  'charged-bodies': people.ruthGarde,
  'the-current-that-kills': people.ruthGarde,
  'dazzling-luxury': people.ruthGarde,
  'titans-in-the-landscape': people.ruthGarde,
  'john-gerrard-frogs-in-space': people.chrisChapman,
  'bill-morrison-domesticating-electricity': people.chrisChapman,
  'camille-henrot-animating-horoscopes': people.chrisChapman,
  'a-body-apart-from-the-head': people.robertBidder,
  'inspired-tattoos-as-pain-relief': people.rockWebb,
  'obsessed-with-buffy-much': people.russellDornan,
  'the-adamson-collection-5womenartists': people.russellDornan,
  'the-phenomenal-dr-price': people.sarahBentley,
  'varieties-of-love': people.sarahJaffray,
  'the-ladies-of-llangollen': people.sarahBentley,
  'queer-territory-claude-cahun-and-a-land-without-labels': people.sarahJaffray,
  'demodicid-navigation': people.robertBidder,
  'body-squabbles-crisps': people.robertBidder,
  'body-squabbles-foot': people.robertBidder,
  'body-squabbles-thirst': people.robertBidder,
  'body-squabbles-teeth': people.robertBidder,
  'body-squabbles-keyholes': people.robertBidder,
  'body-squabbles-pundit': people.robertBidder,
  'body-squabbles-medal': people.robertBidder,
  'museums-in-context-the-birth-of-the-public-museum': people.elissavetNtoulia,
  'the-electric-age': people.lalitaKaplish,
  'electric-age-the-electrified-garden': people.lalitaKaplish,
  'electric-age-hairbrush-wars': people.brionyHudson,
  'electric-age-the-electropoise': people.helenBabbs,
  'electric-age-cornelius-b-harness-and-his-electropathic-belt': people.lalitaKaplish,
  'blackout': people.helenBabbs,
  'creative-energy': people.sarahJames,
  'electropoise': people.helenBabbs,
  'electric-age-condenser-couch': people.dannyBirchall,
  'outsiders-the-stranger': people.annaFaherty,
  'outsiders-the-tradesman': people.annaFaherty,
  'outsiders-the-cook': people.annaFaherty,
  'outsiders-the-colonist': people.annaFaherty,
  'outsiders-the-child': people.annaFaherty,
  'outsiders-the-prostitute': people.annaFaherty,
  'wonder-womans-wonder-women': people.elissavetNtoulia,
  'sharing-nature-wild': people.markThomas
};
