import { createContext } from 'react';
type Props = {
  work: any;
  manifests: any;
  manifestIndex: any;
  setActiveIndex: any;
  mainViewerRef: any;
  viewerRef: any;
  canvases: any;
  gridVisible: any;
  setGridVisible: any;
  viewToggleRef: any;
  currentManifestLabel: any;
  canvasIndex: any;
  licenseInfo: any;
  iiifImageLocationCredit: any;
  downloadOptions: any;
  iiifPresentationDownloadOptions: any;
  parentManifest: any;
  lang: any;
  listHeight: any;
  pageWidth: any;
  setShowZoomed: any;
  setZoomInfoUrl: any;
  setIsLoading: any;
  rotatedImages: any;
  setShowControls: any;
  errorHandler: any;
};
const ItemViewerContext = createContext<Props | null>(null);
export default ItemViewerContext;
