variable "project_name" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_availability_zones" {}
variable "wellcomecollection_key_name" {}
variable "wellcomecollection_key_path" {}
variable "aws_region" {}
variable "aws_node_ami" {}
variable "build_bucket" {}
variable "build_number" {}
variable "build_branch" {}
variable "launch_template" {}
