variable "project_name" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "wellcomecollection_key_name" {}
variable "wellcomecollection_key_path" {}
variable "wellcomecollection_ssl_cert_arn" {}
variable "aws_region" {}
variable "container_tag" {}
variable "container_definitions" {}
