variable "project_name" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "wellcomecollection_key_name" {}
variable "wellcomecollection_key_path" {}
variable "aws_region" {}
variable "aws_node_ami" {}
variable "container_tag" {}
variable "container_definitions" {}
variable "build_state_bucket" {}
