// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgA11YVisual(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M22.54 11.49a11.83 11.83 0 0 0-10.42-6.74A10.9 10.9 0 0 0 7.15 6l-3.6-3.6a1 1 0 1 0-1.41 1.38l14.11 14.11 3.93 3.93a1 1 0 0 0 1.41-1.41l-3.05-3.05a12.7 12.7 0 0 0 4-4.66 1 1 0 0 0 .08-.61 1 1 0 0 0-.08-.6m-5.44 4.42L15.21 14a3.63 3.63 0 0 0-5-5L8.65 7.46a8.9 8.9 0 0 1 3.47-.71 9.78 9.78 0 0 1 8.46 5.35 10.6 10.6 0 0 1-3.48 3.81m-4.98 1.54a9 9 0 0 1-1-.05 9.9 9.9 0 0 1-7.46-5.3q.3-.569.66-1.1a1.002 1.002 0 0 0-1.64-1.15 13.4 13.4 0 0 0-1 1.62 1 1 0 0 0-.08.61 1 1 0 0 0 .08.61 12 12 0 0 0 9.21 6.68q.603.068 1.21.07a1 1 0 0 0 0-2z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgA11YVisual;
