// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgAccessible(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M19.285 11.068a1.2 1.2 0 0 0-.917-.357l-4.143.23 2.28-2.596c.324-.37.417-.863.292-1.304a1.18 1.18 0 0 0-.53-.752l-5.45-3.167a1.19 1.19 0 0 0-1.388.14L6.77 5.635a1.188 1.188 0 1 0 1.582 1.773l2.015-1.797 1.666.967-2.94 3.35a6.06 6.06 0 0 0-3.178 1.57l1.535 1.536a3.9 3.9 0 0 1 2.626-1.017 3.91 3.91 0 0 1 3.907 3.907c0 1.01-.385 1.932-1.016 2.626l1.535 1.536a6.05 6.05 0 0 0 1.65-4.162c0-.96-.222-1.867-.618-2.674l1.604-.09-.39 4.786a1.188 1.188 0 0 0 2.368.193l.5-6.144a1.19 1.19 0 0 0-.332-.926M17.084 5.978a1.989 1.989 0 1 0 0-3.978 1.989 1.989 0 0 0 0 3.978M10.077 19.83a3.91 3.91 0 0 1-3.907-3.907c0-.812.249-1.566.674-2.192L5.292 12.18a6.077 6.077 0 0 0 8.529 8.529l-1.552-1.552a3.9 3.9 0 0 1-2.192.674"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgAccessible;
