// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgAddToClipboard(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M17.75 4.38v-1.1a1 1 0 0 0-1-1h-2a3 3 0 0 0-5.68 0h-2a1 1 0 0 0-1 1v1.1a4 4 0 0 0-3.2 3.92v11.54a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4V8.29a4 4 0 0 0-3.12-3.91zm-9.6-.09H10a1.08 1.08 0 0 0 1-1.09 1 1 0 1 1 2 0v.09a1 1 0 0 0 1 1h1.81v2.14H8.15V4.29zm10.8 15.56a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V8.29a2 2 0 0 1 1.2-1.83v1a1 1 0 0 0 1 1h9.6a1 1 0 0 0 1-1v-1a2 2 0 0 1 1.2 1.83v11.56zM15 10.59l-4.27 4.27L9 13.07a1 1 0 0 0-1.41 1.41l2.37 2.38a1 1 0 0 0 .15.1 1 1 0 0 0 1.41 0l5-5A1.023 1.023 0 0 0 15 10.59z"
      />
    </svg>
  );
}
export default SvgAddToClipboard;
