// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgArchive(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g className="icon__shape" fill="currentColor" fillRule="nonzero">
        <path d="M19.5 4.3h-15a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h15a3 3 0 0 0 3-3v-10a3 3 0 0 0-3-3zm-15 2h15a1 1 0 0 1 1 1v.8h-17v-.8a1 1 0 0 1 1-1zm16 11a1 1 0 0 1-1 1h-15a1 1 0 0 1-1-1v-7.2h17v7.2z" />
        <path d="M14 11.7h-4a2.5 2.5 0 0 0 0 5h4a2.5 2.5 0 1 0 0-5zm0 3h-4a.5.5 0 1 1 0-1h4a.5.5 0 1 1 0 1z" />
      </g>
    </svg>
  );
}
export default SvgArchive;
