// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgArchive(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape">
        <path d="M19.5 4.3h-15a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h15a3 3 0 0 0 3-3v-10a3 3 0 0 0-3-3m-15 2h15a1 1 0 0 1 1 1v.8h-17v-.8a1 1 0 0 1 1-1m16 11a1 1 0 0 1-1 1h-15a1 1 0 0 1-1-1v-7.2h17z" />
        <path d="M14 11.7h-4a2.5 2.5 0 0 0 0 5h4a2.5 2.5 0 1 0 0-5m0 3h-4a.5.5 0 1 1 0-1h4a.5.5 0 1 1 0 1" />
      </g>
    </svg>
  );
}
export default SvgArchive;
