// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgArrowSmall(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="m18.791 11.506-5.224-5.294a.667.667 0 0 0-.975 0 .69.69 0 0 0 0 .988l4.04 4.094H5.697c-.418 0-.697.282-.697.706s.279.706.697.706h10.935l-4.04 4.094a.69.69 0 0 0 0 .988.75.75 0 0 0 .488.212c.139 0 .348-.07.487-.212l5.224-5.294a.69.69 0 0 0 0-.988"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgArrowSmall;
