// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgArticle(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape">
        <path d="M19 3.37H6.5a3 3 0 0 0-3 3v12.55a3 3 0 0 0 3 3H19a3 3 0 0 0 3-3V6.37a3 3 0 0 0-3-3m1 15.55a1 1 0 0 1-1 1H6.5a1 1 0 0 1-1-1V6.37a1 1 0 0 1 1-1H19a1 1 0 0 1 1 1z" />
        <path d="M7.48 11.81h4.96v2H7.48zm0-4.43h10.29v2H7.48zm0 8.85h4.96v2H7.48zm6.54-4.5h3.8v6.44h-3.8z" />
      </g>
    </svg>
  );
}
export default SvgArticle;
