// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgAudioDescribedSquare(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 24 24"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      {...props}
    >
      <g clipPath="url(#a)">
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M3 0a3 3 0 0 0-3 3v18a3 3 0 0 0 3 3h18a3 3 0 0 0 3-3V3a3 3 0 0 0-3-3zm15.78 4.53H5.22c-1.006 0-1.495.41-1.495 1.239v9.165c0 .839.489 1.238 1.495 1.238h8.797l3.172 2.691v-2.69h1.59c1.007 0 1.496-.42 1.496-1.239V5.769c0-.839-.489-1.238-1.495-1.238m.757 13.153c1.36 0 2.463-.945 2.463-2.105V5.106C22 3.946 20.907 3.01 19.556 3H4.444C3.102 3 2 3.946 2 5.106v10.472c0 1.17 1.102 2.105 2.444 2.105h8.028l6.433 4.817v-4.817zM9.368 11.47H7.606L8.5 8.702zm.41.936.446 1.442h1.57L9.357 6.844H7.708l-2.477 7.003h1.52l.472-1.442zm5.85-4.314c.65 0 1.11.182 1.327.572s.32.805.32 1.52c0 .714-.064.974-.218 1.338-.268.676-.74 1.026-1.43 1.026h-1.34V8.091zm.255 5.756c1.047 0 1.826-.442 2.324-1.3.357-.636.562-1.429.562-2.364 0-.703-.022-.775-.07-.938a3 3 0 0 1-.058-.218 3.1 3.1 0 0 0-.498-1.13h-.013c-.306-.442-.69-.741-1.175-.897-.293-.104-.638-.156-1.072-.156h-2.989v7.003z"
          className="icon__shape"
          clipRule="evenodd"
        />
      </g>
      <defs>
        <clipPath id="a">
          <path d="M0 0h24v24H0z" />
        </clipPath>
      </defs>
    </svg>
  );
}
export default SvgAudioDescribedSquare;
