// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgAudioDescribed(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M5.22 4.53h13.56c1.006 0 1.495.4 1.495 1.239v9.165c0 .819-.489 1.238-1.495 1.238h-1.59v2.691l-3.173-2.69H5.22c-1.006 0-1.495-.4-1.495-1.239V5.769c0-.829.489-1.238 1.495-1.238M22 15.579c0 1.16-1.102 2.105-2.463 2.105h-.632V22.5l-6.433-4.817H4.444C3.102 17.684 2 16.748 2 15.578V5.106C2 3.946 3.102 3 4.444 3h15.112C20.907 3.01 22 3.946 22 5.106zM7.606 11.469h1.762L8.5 8.702zm2.618 2.378-.447-1.442H7.223l-.472 1.442H5.23l2.477-7.003h1.648l2.439 7.003zm6.731-5.184c-.217-.39-.677-.572-1.328-.572h-1.34v4.456h1.34c.69 0 1.162-.35 1.43-1.026.154-.364.218-.624.218-1.338s-.103-1.13-.32-1.52m1.252 3.884c-.498.858-1.277 1.3-2.324 1.3h-2.989V6.844h2.989c.434 0 .779.052 1.072.156.486.156.869.455 1.175.896h.013c.242.338.409.728.498 1.13.022.1.041.165.057.219.049.163.07.235.07.938 0 .935-.204 1.728-.561 2.364"
        className="icon__shape"
        clipRule="evenodd"
      />
    </svg>
  );
}
export default SvgAudioDescribed;
