// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgAudioDescribed(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M8.532 10.971h1.323l-.652-2.077zm1.965 1.784-.335-1.082H8.245l-.355 1.082H6.75L8.61 7.5h1.235l1.83 5.255zM15.892 8.865c-.163-.292-.508-.429-.996-.429h-1.007v3.344h1.007c.517 0 .872-.263 1.073-.77.115-.273.163-.468.163-1.004 0-.537-.077-.848-.24-1.141m.94 2.915c-.374.644-.959.975-1.745.975h-2.242V7.5h2.242c.326 0 .585.039.805.117.364.117.652.341.882.673h.01c.182.253.306.546.373.848.017.075.031.123.043.164.037.122.053.177.053.704 0 .702-.153 1.297-.422 1.774"
        className="icon__shape"
        clipRule="evenodd"
      />
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M17.78 4.53H6.22c-1.006 0-1.495.41-1.495 1.239v9.165c0 .839.489 1.238 1.495 1.238h6.797l3.172 2.691v-2.69h1.59c1.007 0 1.496-.42 1.496-1.239V5.769c0-.839-.489-1.238-1.495-1.238m.757 13.153c1.36 0 2.463-.945 2.463-2.105V5.106C21 3.946 19.907 3.01 18.556 3H5.444C4.102 3 3 3.946 3 5.106v10.472c0 1.17 1.102 2.105 2.444 2.105h6.028l6.433 4.817v-4.817z"
        className="icon__shape"
        clipRule="evenodd"
      />
    </svg>
  );
}
export default SvgAudioDescribed;
