// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgAudio(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape">
        <path d="M20.65 3.8H3.95a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2h16.7a2 2 0 0 0 2-2v-13a2 2 0 0 0-2-2m-16.7 15v-13h16.7v13z" />
        <path d="M11.95 10.55a.75.75 0 0 0-.75.75v2a.75.75 0 1 0 1.5 0v-2a.75.75 0 0 0-.75-.75m3.15-2a.75.75 0 0 0-.75.75v6a.75.75 0 0 0 1.5 0v-6a.75.75 0 0 0-.75-.75m3.15-1a.75.75 0 0 0-.75.75v8a.75.75 0 1 0 1.5 0v-8a.75.75 0 0 0-.75-.75M9.34 8a1 1 0 0 0-1.12.4l-.9 1.35H6a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h1.31l.9 1.35a1 1 0 0 0 .83.45 1 1 0 0 0 .29 0 1 1 0 0 0 .71-1V9a1 1 0 0 0-.7-1" />
      </g>
    </svg>
  );
}
export default SvgAudio;
