// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgAudioDescribed(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g className="icon__shape" fill="currentColor" fillRule="nonzero">
        <path d="M15.932 9.102h-1.467v5.953h1.846c1.19 0 2.326-.738 2.326-2.833-.019-1.902-.674-3.12-2.705-3.12zm-8.806.581l-1.21 3.462h2.41L7.154 9.683h-.028z" />
        <path d="M20.695 0H3.305A3.305 3.305 0 0 0 0 3.305v17.39A3.305 3.305 0 0 0 3.305 24h17.39A3.305 3.305 0 0 0 24 20.695V3.305A3.305 3.305 0 0 0 20.695 0zM9.563 16.8l-.701-2.105h-3.48L4.615 16.8h-2.04l3.536-9.415h2.095l3.49 9.415H9.562zm6.868 0h-4.016V7.385h4.016c2.418 0 4.227 1.532 4.227 4.67.01 2.714-1.375 4.745-4.218 4.745h-.01z" />
      </g>
    </svg>
  );
}
export default SvgAudioDescribed;
