// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgBook(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M20 3.3h-4.88A4.17 4.17 0 0 0 12 5.09 4.16 4.16 0 0 0 8.88 3.3H4a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h4.88a2.29 2.29 0 0 1 2.19 1.34v.07a1 1 0 0 0 .17.23l.06.05a1 1 0 0 0 .28.18 1 1 0 0 0 .34.07h.31l.09-.05a1 1 0 0 0 .19-.12l.11-.1a1.67 1.67 0 0 0 .19-.29A2.3 2.3 0 0 1 15 18.34h5a2 2 0 0 0 2-2v-11a2 2 0 0 0-2-2.04zm0 13h-4.88A4.25 4.25 0 0 0 12 17.55a4.25 4.25 0 0 0-3.12-1.25L4 16.32V5.3h4.88A2.78 2.78 0 0 1 11 7.8v7a1 1 0 0 0 2 0v-7a2.77 2.77 0 0 1 2.12-2.5H20v11z"
      />
    </svg>
  );
}
export default SvgBook;
