// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgCalendarAdded(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M10.59 19.88a1 1 0 0 0 1.41 0l5-5a1 1 0 0 0-1.41-1.41l-4.33 4.33-1.49-1.49a1 1 0 0 0-1.41 1.41z"
        className="icon__shape"
      />
      <path
        fill="currentColor"
        d="M18 4.42v-1.5a1 1 0 0 0-2 0v1.5H8v-1.5a1 1 0 1 0-2 0v1.5a4 4 0 0 0-4 4v11a4 4 0 0 0 4 4h12a4 4 0 0 0 4-4v-11a4 4 0 0 0-4-4m-14 4a2 2 0 0 1 2-2v1.5a1 1 0 1 0 2 0v-1.5h8v1.5a1 1 0 0 0 2 0v-1.5a2 2 0 0 1 2 2v1.5H4zm16 11a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-7.5h16z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgCalendarAdded;
