// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgCheck(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M21.13 6.64a1 1 0 0 0-1.41 0L10 16.34l-5-5a1 1 0 0 0-1.41 1.41l5.67 5.67a1 1 0 0 0 1.41 0l10.4-10.4a1 1 0 0 0 .06-1.38z"
      />
    </svg>
  );
}
export default SvgCheck;
