// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgChevrons(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      viewBox="0 0 24 24"
      {...props}
    >
      <path
        className="icon__shape"
        fill="currentColor"
        d="M11.2,19.3c-0.4,0-0.7-0.1-0.9-0.4l-6-6c-0.5-0.5-0.5-1.4,0-1.9l6-6c0.5-0.5,1.4-0.5,1.9,0s0.5,1.4,0,1.9L7.1,12l5.1,5.1 c0.5,0.5,0.5,1.4,0,1.9C11.9,19.2,11.5,19.3,11.2,19.3z"
      />
      <path
        className="icon__shape"
        fill="currentColor"
        d="M18.8,19.3c-0.4,0-0.7-0.1-0.9-0.4l-6-6c-0.5-0.5-0.5-1.4,0-1.9l6-6c0.5-0.5,1.4-0.5,1.9,0c0.5,0.5,0.5,1.4,0,1.9L14.7,12 l5.1,5.1c0.5,0.5,0.5,1.4,0,1.9C19.5,19.2,19.2,19.3,18.8,19.3z"
      />
    </svg>
  );
}
export default SvgChevrons;
