// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgChevrons(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M11.2 19.3c-.4 0-.7-.1-.9-.4l-6-6c-.5-.5-.5-1.4 0-1.9l6-6c.5-.5 1.4-.5 1.9 0s.5 1.4 0 1.9L7.1 12l5.1 5.1c.5.5.5 1.4 0 1.9-.3.2-.7.3-1 .3"
      />
      <path
        fill="currentColor"
        d="M18.8 19.3c-.4 0-.7-.1-.9-.4l-6-6c-.5-.5-.5-1.4 0-1.9l6-6c.5-.5 1.4-.5 1.9 0s.5 1.4 0 1.9L14.7 12l5.1 5.1c.5.5.5 1.4 0 1.9-.3.2-.6.3-1 .3"
      />
    </svg>
  );
}
export default SvgChevrons;
