// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgClock(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape">
        <path d="M11.9 2.1a10.17 10.17 0 1 0 10.17 10.16C22.059 6.65 17.51 2.106 11.9 2.1m0 18.33a8.17 8.17 0 1 1 0-16.34 8.17 8.17 0 0 1 0 16.34" />
        <path d="M15.83 12.06h-3v-4.5a1 1 0 0 0-2 0v5.5a1 1 0 0 0 1 1h4a1 1 0 0 0 0-2" />
      </g>
    </svg>
  );
}
export default SvgClock;
