// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgClosedFolder(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M2.4 21.6c-.66 0-1.22-.23-1.69-.71C.24 20.42 0 19.86 0 19.2V4.8c0-.66.24-1.22.71-1.7.47-.47 1.03-.7 1.69-.7h7.2L12 4.8h9.6c.66 0 1.23.24 1.7.71s.71 1.03.71 1.69v12c0 .66-.24 1.22-.71 1.69s-1.03.71-1.7.71z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgClosedFolder;
