// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgClosedFolder(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      fill="none"
      viewBox="0 0 24 24"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      {...props}
    >
      <defs>
        <path fill="currentColor" d="M0 .5h24v24H0z" id="reuse-0" />
      </defs>
      <mask
        id="a"
        width={24}
        height={24}
        x={0}
        y={0}
        maskUnits="userSpaceOnUse"
        style={{
          maskType: 'alpha',
        }}
      >
        <use xlinkHref="#reuse-0" />
      </mask>
      <g mask="url(#a)">
        <mask
          id="b"
          width={24}
          height={24}
          x={0}
          y={0}
          maskUnits="userSpaceOnUse"
          style={{
            maskType: 'alpha',
          }}
        >
          <use xlinkHref="#reuse-0" />
        </mask>
        <g mask="url(#b)">
          <path
            fill="currentColor"
            d="M2.665 13.833q-.55 0-.941-.391a1.28 1.28 0 0 1-.392-.942v-8q0-.55.392-.942.391-.39.941-.391h4L8 4.5h5.333q.55 0 .942.392.39.391.391.941V12.5q0 .55-.391.942a1.28 1.28 0 0 1-.942.391z"
            className="icon__shape"
          />
        </g>
      </g>
    </svg>
  );
}
export default SvgClosedFolder;
