// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgCollapse(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M7.4 20.6h1.9v-5c0-.6-.4-1-1-1h-5v1.9h4zM8.4 9.3c.6 0 1-.4 1-1v-5h-2v4h-4v2zM16.6 20.6v-4h4v-2h-5c-.6 0-1 .4-1 1v5zM16.6 3.4h-1.9v5c0 .6.4 1 1 1h5v-2h-4z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgCollapse;
