// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgCollapse(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M5.66 24h2.62v-6.91c0-.83-.55-1.38-1.38-1.38H0v2.62h5.53l.14 5.66ZM6.91 8.29c.83 0 1.38-.55 1.38-1.38V0H5.53v5.53H0v2.76zM18.47 24v-5.53H24v-2.76h-6.91c-.83 0-1.38.55-1.38 1.38V24zM18.34 0h-2.62v6.91c0 .83.55 1.38 1.38 1.38h6.91V5.53h-5.53z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgCollapse;
