// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgComments(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape">
        <path d="M19 2.46H5a3 3 0 0 0-3 3v16a1 1 0 0 0 1.37.93l4.82-1.93H19a3 3 0 0 0 3-3v-12a3 3 0 0 0-3-3m1 15a1 1 0 0 1-1 1H8a1 1 0 0 0-.16 0 1 1 0 0 0-.21 0L4 20V5.46a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1z" />
        <path d="M6 6.46h12v2H6zm0 4h12v2H6zm0 4h8v2H6z" />
      </g>
    </svg>
  );
}
export default SvgComments;
