// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgCookies(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        transform="translate(1 1)"
      >
        <path d="M21.51 10.94a.9.9 0 0 0-.81-.88 3.84 3.84 0 0 1-3.23-2.51.9.9 0 0 0-1.31-.47 3.78 3.78 0 0 1-1.95.55 3.84 3.84 0 0 1-3.84-3.84 3.78 3.78 0 0 1 .43-1.71.9.9 0 0 0-.07-.92.87.87 0 0 0-.84-.38 10.42 10.42 0 1 0 11.63 10.34s0-.12-.01-.18zm-10.41 8.8A8.62 8.62 0 0 1 8.66 2.86a5.34 5.34 0 0 0-.08.93 5.65 5.65 0 0 0 5.64 5.64 5.52 5.52 0 0 0 2-.37 5.66 5.66 0 0 0 3.51 2.65 8.63 8.63 0 0 1-8.63 8.03z" />
        <circle cx={5.78} cy={10.24} r={1.25} />
        <circle cx={15.26} cy={3.8} r={1.25} />
        <circle cx={9.63} cy={11.6} r={1.25} />
        <circle cx={12.49} cy={16.11} r={1.25} />
      </g>
    </svg>
  );
}
export default SvgCookies;
