// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgCopyEmail(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M9.09 6.43a8.44 8.44 0 0 0-8.55 8.32 8.44 8.44 0 0 0 8.55 8.31 8.75 8.75 0 0 0 4.16-1l-1-2.08a6.17 6.17 0 0 1-9.34-5.18 6.165 6.165 0 1 1 12.33 0c0 1.61-.59 2.66-1.56 2.66-.52 0-1-.37-1-1.47V13.5c0-2-1.43-3-3.36-3a7.3 7.3 0 0 0-3.46 1l.91 1.77a7.2 7.2 0 0 1 2.59-.59c.35 0 1 .09 1 .58s-.54.46-.91.46c-1.66 0-3.92.21-3.92 2.55C5.49 18.11 7 19 8.69 19c1.08 0 1.66-.38 2.29-.38a1 1 0 0 1 .72.26 3.08 3.08 0 0 0 2 .73c2.19 0 3.88-1.92 3.88-4.88a8.44 8.44 0 0 0-8.49-8.3m-.21 10.63c-.65 0-1-.35-1-.72s.4-.8 1.15-.8a4.3 4.3 0 0 0 1.21-.14v.52a5 5 0 0 0 .14.93 7.4 7.4 0 0 1-1.5.21m14-12.61h-2.66v-2.6a1 1 0 0 0-2 0v2.61h-2.61a1 1 0 0 0 0 2h2.61v2.61a1 1 0 0 0 2 0V6.46h2.61a1 1 0 0 0 0-2z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgCopyEmail;
