// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgDigitalImage(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        d="M14.08 2.83H8a3 3 0 0 0-3 3v12a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V7.75zM17 8.58v.75h-2.33a1 1 0 0 1-1-1V5.25zm-1 10.25H8a1 1 0 0 1-1-1v-12a1 1 0 0 1 1-1h3.67v3.5a3 3 0 0 0 3 3H17v6.5a1 1 0 0 1-1 1z"
      />
    </svg>
  );
}
export default SvgDigitalImage;
