// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgDocument(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g className="icon__shape" fill="currentColor" fillRule="nonzero">
        <path d="M18.11 1.55a1 1 0 0 0-1 1V5.1H3.7a2 2 0 0 0-2 2v13a1 1 0 0 0 .33.73c.059.09.126.173.2.25a3 3 0 0 0 2.2.62h.27a1 1 0 0 0 1-1v-.6h13.8a3 3 0 0 0 3-2.75.94.94 0 0 0 0-.13V5.52c0-2.93-2.27-3.97-4.39-3.97zm2.39 4v7.87a4.44 4.44 0 0 0-1.34-.51V3.69a1.72 1.72 0 0 1 1.34 1.83v.03zm-1 12.58H3.7V7.1h13.43v6.69a1 1 0 0 0 1 1 2.17 2.17 0 0 1 2.33 2.36 1 1 0 0 1-.96.95v.03z" />
        <path d="M5.7 8.6h2v8h-2v-8zm3.79 0h2v8h-2v-8zm3.78 0h2v8h-2v-8z" />
      </g>
    </svg>
  );
}
export default SvgDocument;
