// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgDocument(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape">
        <path d="M18.11 1.55a1 1 0 0 0-1 1V5.1H3.7a2 2 0 0 0-2 2v13a1 1 0 0 0 .33.73q.089.135.2.25a3 3 0 0 0 2.2.62h.27a1 1 0 0 0 1-1v-.6h13.8a3 3 0 0 0 3-2.75 1 1 0 0 0 0-.13V5.52c0-2.93-2.27-3.97-4.39-3.97m2.39 4v7.87a4.4 4.4 0 0 0-1.34-.51V3.69a1.72 1.72 0 0 1 1.34 1.83zm-1 12.58H3.7V7.1h13.43v6.69a1 1 0 0 0 1 1 2.17 2.17 0 0 1 2.33 2.36 1 1 0 0 1-.96.95z" />
        <path d="M5.7 8.6h2v8h-2zm3.79 0h2v8h-2zm3.78 0h2v8h-2z" />
      </g>
    </svg>
  );
}
export default SvgDocument;
