// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgDuration(props: SVGProps<SVGSVGElement>) {
  return (
    <svg fill="currentColor" viewBox="0 0 24 24" {...props}>
      <path
        fillRule="evenodd"
        d="M12.138 2C6.6 2 2 6.493 2 12c0 5.523 4.477 10 10 10s10-4.477 10-10a1 1 0 1 1 2 0c0 6.627-5.373 12-12 12S0 18.627 0 12C0 5.356 5.527 0 12.138 0c3.787 0 7.164 1.755 9.362 4.492V3a1 1 0 1 1 2 0v4a1 1 0 0 1-1 1h-4a1 1 0 1 1 0-2h1.64a9.98 9.98 0 0 0-8.002-4M10 8a1 1 0 1 1 2 0v5h5a1 1 0 1 1 0 2h-6a1 1 0 0 1-1-1V8"
        className="icon__shape"
        clipRule="evenodd"
      />
    </svg>
  );
}
export default SvgDuration;
