// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgEdit(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M3 7h10.37a1 1 0 0 0 0-2H3a1 1 0 1 0 0 2zm0 4.61h5.67a1 1 0 1 0 0-2H3a1 1 0 1 0 0 2zm1.87 2.63H3a1 1 0 0 0 0 2h1.87a1 1 0 0 0 0-2zm17.3-6.04l-3-3a1 1 0 0 0-1.41 0l-8.21 8.21a1 1 0 0 0 0 1.41l3 3a1 1 0 0 0 1.41 0l8.21-8.21a1 1 0 0 0 0-1.41zm-8.92 7.51l-1.59-1.59 4.2-4.2 1.59 1.59-4.2 4.2zm5.62-5.62l-1.6-1.59 1.18-1.18L20 8.91l-1.13 1.18zm-8.05 8.03l-2 .45.45-2a1.023 1.023 0 0 0-2-.43l-.78 3.55a5.51 5.51 0 0 0 0 .4 1 1 0 0 0 .13.32 1 1 0 0 0 .23.25l.1.05a1 1 0 0 0 .24.1h.42l3.55-.78a1.023 1.023 0 0 0-.43-2l.09.09z"
      />
    </svg>
  );
}
export default SvgEdit;
