// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgEdit(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M3 7h10.37a1 1 0 0 0 0-2H3a1 1 0 1 0 0 2m0 4.61h5.67a1 1 0 1 0 0-2H3a1 1 0 1 0 0 2m1.87 2.63H3a1 1 0 0 0 0 2h1.87a1 1 0 0 0 0-2m17.3-6.04-3-3a1 1 0 0 0-1.41 0l-8.21 8.21a1 1 0 0 0 0 1.41l3 3a1 1 0 0 0 1.41 0l8.21-8.21a1 1 0 0 0 0-1.41m-8.92 7.51-1.59-1.59 4.2-4.2 1.59 1.59zm5.62-5.62-1.6-1.59 1.18-1.18L20 8.91zm-8.05 8.03-2 .45.45-2a1.023 1.023 0 0 0-2-.43l-.78 3.55a6 6 0 0 0 0 .4 1 1 0 0 0 .13.32 1 1 0 0 0 .23.25l.1.05a1 1 0 0 0 .24.1h.42l3.55-.78a1.023 1.023 0 0 0-.43-2z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgEdit;
