// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgExclamation(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M13 18a1 1 0 1 1-2 0 1 1 0 0 1 2 0M12 5c-.816 0-1.466.683-1.425 1.498l.375 7.503a1.051 1.051 0 0 0 2.1 0l.375-7.503A1.427 1.427 0 0 0 12 5"
        className="icon__shape"
      />
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12s5.373 12 12 12m0-2c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgExclamation;
