// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { IconSvg } from '../types';

const SvgExclamation: IconSvg = props => (
  <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      className="icon__shape"
      fill="currentColor"
      fillRule="nonzero"
      d="M13 18C13 18.5523 12.5523 19 12 19C11.4477 19 11 18.5523 11 18C11 17.4477 11.4477 17 12 17C12.5523 17 13 17.4477 13 18Z"
    />
    <path
      className="icon__shape"
      fill="currentColor"
      fillRule="nonzero"
      d="M12 5C11.184 5 10.5342 5.68312 10.5749 6.49813L10.9501 14.0012C10.978 14.5607 11.4398 15 12 15C12.5602 15 13.022 14.5607 13.0499 14.0012L13.4251 6.49813C13.4658 5.68312 12.816 5 12 5Z"
    />
    <path
      className="icon__shape"
      fill="currentColor"
      fillRule="evenodd"
      d="M12 24C18.6274 24 24 18.6274 24 12C24 5.37258 18.6274 0 12 0C5.37258 0 0 5.37258 0 12C0 18.6274 5.37258 24 12 24ZM12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z"
    />
  </svg>
);

export default SvgExclamation;
