// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgExpand(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M19.07 11.2a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1h-5a1 1 0 1 0 0 2h2.59L12 10.88 7.29 6.2h2.78a1 1 0 1 0 0-2h-5a1 1 0 0 0-1 1v5a1 1 0 1 0 2 0V7.81l4.49 4.49-4.49 4.49V14.2a1 1 0 1 0-2 0v5a1 1 0 0 0 1 1h5a1 1 0 0 0 0-2H7.48L12 13.71l4.49 4.49h-2.42a1 1 0 0 0 0 2h5a1 1 0 0 0 1-1v-5a1 1 0 0 0-2 0V17l-4.69-4.7 4.68-4.68v2.58a1 1 0 0 0 1.01 1z"
      />
    </svg>
  );
}
export default SvgExpand;
