// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgEye(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape" transform="translate(2 4)">
        <path d="M10 0C4.17 0 0 6 0 8s4 8 10 8 10-6 10-8-4.2-8-10-8m0 14c-4.76 0-8-5-8-6s3.21-6 8-6 8 5.11 8 6-3.24 6-8 6" />
        <circle cx={9.97} cy={8} r={3} />
      </g>
    </svg>
  );
}
export default SvgEye;
