// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgFamily(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M18.2 12.5c1.9-1.7 2.6-4.4 1.7-6.8s-3.2-4-5.8-4-4.9 1.6-5.8 4c-.4 1-.5 2.1-.3 3.2-.3-.1-.7-.1-1-.1-2.3 0-4.1 1.9-4.1 4.1 0 1.2.6 2.3 1.4 3.1-1.3.5-2.3 1.4-3.1 2.7-.2.3-.2.6-.3.9l-.1 1.2v.1c0 .8.7 1.5 1.5 1.5h18c.9 0 1.7-.4 2.3-1 .6-.7.9-1.5.8-2.4-.4-3-1.5-5.5-5.2-6.5m-4.1-8.7c2.3 0 4.1 1.9 4.1 4.1S16.3 12 14.1 12 10 10.1 10 7.9s1.8-4.1 4.1-4.1m-7.2 6.6c1.4 0 2.5 1.1 2.5 2.5s-1.1 2.5-2.5 2.5-2.5-1.1-2.5-2.5 1.1-2.5 2.5-2.5M2.5 20.6l.1-.9v-.1c.9-1.6 2.2-2.3 4.1-2.3s3.2.7 4.1 2.3v.1l.1.9zM21 20c-.2.2-.5.4-.8.3h-7.4l-.1-.8q0-.45-.3-.9c-.7-1.3-1.7-2.1-2.9-2.7.5-.4.9-1 1.2-1.6.9-.2 2-.4 3.4-.4 6.1 0 6.9 2.4 7.2 5.1 0 .5-.1.8-.3 1"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgFamily;
