// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgFile(props: SVGProps<SVGSVGElement>) {
  return (
    <svg fill="none" viewBox="0 0 24 24" {...props}>
      <mask
        id="a"
        width={24}
        height={24}
        x={0}
        y={0}
        maskUnits="userSpaceOnUse"
        style={{
          maskType: 'alpha',
        }}
      >
        <path fill="currentColor" d="M0 0h24v24H0z" />
      </mask>
      <g mask="url(#a)">
        <path
          fill="currentColor"
          d="M5.335 12h5.333v-1.333H5.335zm0-2.667h5.333V8H5.335zM4 14.667q-.55 0-.941-.392a1.28 1.28 0 0 1-.392-.942V2.667q0-.55.392-.942.391-.392.941-.392h5.334l4 4v8q0 .55-.392.942a1.28 1.28 0 0 1-.942.392zM8.668 6V2.667H4.001v10.666h8V6z"
          className="icon__shape"
        />
      </g>
    </svg>
  );
}
export default SvgFile;
