// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgFile(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M7.2 19.2h9.6v-2.4H7.2zm0-4.8h9.6V12H7.2zM4.8 24c-.66 0-1.22-.24-1.69-.71a2.32 2.32 0 0 1-.71-1.69V2.4c0-.66.23-1.23.71-1.7.47-.47 1.03-.71 1.69-.71h9.6l7.2 7.2v14.4c0 .66-.23 1.22-.7 1.69s-1.03.71-1.7.71H4.8Zm8.4-15.6v-6H4.8v19.2h14.4V8.4z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgFile;
