// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgFilter(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 72 72" {...props}>
      <path
        fill="currentColor"
        d="M44 10a12 12 0 0 0-11.6 9H11a3 3 0 0 0 0 6h21.4A12 12 0 1 0 44 10m0 18a6 6 0 1 1 6-6 6 6 0 0 1-6 6"
        className="icon__shape"
      />
      <path
        fill="currentColor"
        d="M61 25h-5a3 3 0 0 1 0-6h5a3 3 0 0 1 0 6M61 47H39.6a12 12 0 0 0-23.22 0 3 3 0 0 0-.38 0h-5a3 3 0 0 0 0 6h5a3 3 0 0 0 .38 0 12 12 0 0 0 23.22 0H61a3 3 0 0 0 0-6m-33 9a6 6 0 1 1 6-6 6 6 0 0 1-6 6"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgFilter;
