// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgFolder(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M22.8 10.46a1 1 0 0 0-.8-.4h-1.74v-1.6a2 2 0 0 0-2-2h-7.47V5.2c0-.9-.73-1.63-1.63-1.63H3.29c-.9 0-1.63.73-1.63 1.63V20a2 2 0 0 0 2 2H18.3a2 2 0 0 0 1.92-1.57L23 11.35a1 1 0 0 0-.2-.89zM3.66 5.57h5.13v1.92a1 1 0 0 0 1 1h8.47v1.6H5.56a1 1 0 0 0-1 .71l-.93 3.11V5.57h.03zm14.72 14v.05l-.06.21a.94.94 0 0 0 0 .14L3.9 20l2.4-8h14.35l-2.27 7.57z"
      />
    </svg>
  );
}
export default SvgFolder;
