// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgGalleryFilled(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g className="icon__shape" fill="currentColor" fillRule="nonzero">
        <path d="M20.1 3.6H7.2c-.6 0-1 .4-1 1s.4 1 1 1h12.9c.4 0 .7.3.7.7v8.6c0 .6.4 1 1 1s1-.4 1-1V6.3c0-1.5-1.2-2.7-2.7-2.7z" />
        <path d="M16.7 7H3.9C2.4 7 1.2 8.2 1.2 9.7v8.6c0 1.5 1.2 2.7 2.7 2.7h12.8c1.5 0 2.7-1.2 2.7-2.7V9.7c0-1.5-1.2-2.7-2.7-2.7z" />
      </g>
    </svg>
  );
}
export default SvgGalleryFilled;
