// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgGrayscale(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M5 4h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1m1 2v12h12V6zm2 2h2v8H8zm4 0h2v8h-2zm4 0v8h-2V8z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgGrayscale;
