// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgHearingLoop(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g className="icon__shape" fill="currentColor" fillRule="nonzero">
        <path d="M9.16 9.57a2.25 2.25 0 1 1 4.5 0 1 1 0 0 0 2 0 4.25 4.25 0 1 0-8.5 0 1 1 0 0 0 2 0zm1.02 2.76a1 1 0 0 0-1.41 0l-6.35 6.35a1 1 0 1 0 1.41 1.41l6.35-6.35a1 1 0 0 0 0-1.41zM21.78.73a1 1 0 0 0-1.41 0l-2.21 2.21a1 1 0 1 0 1.41 1.41l2.21-2.21a1 1 0 0 0 0-1.41z" />
        <path d="M11.41 1.72a7.68 7.68 0 0 0-7.67 7.67 1 1 0 1 0 2 0 5.67 5.67 0 1 1 9.18 4.45l-1.53 1.24a6.47 6.47 0 0 0-1.76 4.48v.33c0 .86-.48 1.5-.92 1.5H9.4a1 1 0 0 0 0 2h1.32a3.25 3.25 0 0 0 2.92-3.5v-.33a4.67 4.67 0 0 1 1-2.95l1.5-1.22a7.67 7.67 0 0 0-4.73-13.67z" />
      </g>
    </svg>
  );
}
export default SvgHearingLoop;
