// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgHome(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      fill="currentColor"
      className="icon__shape"
      viewBox="0 0 22 22"
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M12.233.425a2 2 0 0 0-2.466 0l-9 7.044A2 2 0 0 0 0 9.044V20a2 2 0 0 0 2 2h5a2 2 0 0 0 2-2v-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v5a2 2 0 0 0 2 2h5a2 2 0 0 0 2-2V9.044a2 2 0 0 0-.767-1.575zM15 18.951a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1V9.667a1 1 0 0 0-.376-.781l-8-6.388a1 1 0 0 0-1.248 0l-8 6.388A1 1 0 0 0 2 9.667v9.284a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1V14a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2z"
        clipRule="evenodd"
      />
    </svg>
  );
}
export default SvgHome;
