// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgImageFile(props: SVGProps<SVGSVGElement>) {
  return (
    <svg fill="none" viewBox="0 0 24 24" {...props}>
      <mask
        id="a"
        width={24}
        height={24}
        x={0}
        y={0}
        maskUnits="userSpaceOnUse"
        style={{
          maskType: 'alpha',
        }}
      >
        <path fill="currentColor" d="M0 0h24v24H0z" />
      </mask>
      <g mask="url(#a)">
        <path
          fill="currentColor"
          d="M3.333 14q-.55 0-.941-.392A1.28 1.28 0 0 1 2 12.667V3.333q0-.55.392-.941Q2.783 2 3.333 2h9.334q.55 0 .941.392.392.391.392.941v9.334q0 .55-.392.941a1.28 1.28 0 0 1-.941.392zm0-1.333h9.334V3.333H3.333zM4 11.333h8L9.5 8l-2 2.667-1.5-2zm1.667-4.666a.96.96 0 0 0 .708-.292.96.96 0 0 0 .292-.708.96.96 0 0 0-.292-.709.96.96 0 0 0-.708-.291.96.96 0 0 0-.709.291.96.96 0 0 0-.291.709q0 .416.291.708.292.291.709.292"
          className="icon__shape"
        />
      </g>
    </svg>
  );
}
export default SvgImageFile;
