// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgImageFile(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M2.67 24c-.73 0-1.36-.26-1.88-.78s-.78-1.15-.78-1.88V2.67c0-.73.26-1.36.78-1.88S1.94.01 2.67.01h18.67c.73 0 1.36.26 1.88.78S24 1.94 24 2.67v18.67c0 .73-.26 1.36-.78 1.88s-1.15.78-1.88.78zm0-2.67h18.67V2.67H2.67v18.67ZM4 18.67h16L15 12l-4 5.33-3-4-4 5.33Zm3.33-9.34c.56 0 1.03-.19 1.42-.58s.58-.86.58-1.42-.19-1.03-.58-1.42-.86-.58-1.42-.58-1.03.19-1.42.58-.58.86-.58 1.42.19 1.03.58 1.42.86.58 1.42.58"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgImageFile;
