// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgIndicator(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <circle
        cx={10}
        cy={10}
        r={10}
        fill="currentColor"
        className="icon__shape"
        transform="translate(2 2)"
      />
    </svg>
  );
}
export default SvgIndicator;
