// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgInductionLoop(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M10.137 9.96c0-1.08.838-1.961 1.867-1.961 1.03 0 1.868.88 1.868 1.96 0 .483.37.872.83.872s.83-.39.83-.871c0-2.043-1.582-3.704-3.528-3.704S8.477 7.917 8.477 9.96c0 .482.371.871.83.871s.83-.39.83-.871M10.986 12.364a.8.8 0 0 0-1.173 0l-5.27 5.534a.903.903 0 0 0 0 1.232.8.8 0 0 0 .586.256.8.8 0 0 0 .587-.256l5.27-5.533a.9.9 0 0 0 0-1.233M20.613 2.256a.8.8 0 0 0-1.173 0l-1.836 1.927a.9.9 0 0 0 0 1.233c.162.17.374.255.587.255a.8.8 0 0 0 .587-.256l1.835-1.927a.9.9 0 0 0 0-1.232"
        className="icon__shape"
        clipRule="evenodd"
      />
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M5.641 9.8c0 .481.371.87.83.87.46 0 .83-.389.83-.87 0-2.724 2.11-4.94 4.704-4.94 2.592 0 4.702 2.216 4.702 4.94 0 1.513-.648 2.923-1.786 3.873l-1.268 1.082c-.832.757-1.46 2.434-1.46 3.905v.29c0 .748-.402 1.307-.761 1.307h-1.093c-.459 0-.83.39-.83.871 0 .482.371.872.83.872h1.093c1.335 0 2.421-1.368 2.421-3.05v-.29c0-1.02.467-2.205.867-2.568l1.241-1.06c1.529-1.277 2.406-3.184 2.406-5.233 0-3.684-2.853-6.681-6.362-6.681S5.64 6.115 5.64 9.799"
        className="icon__shape"
        clipRule="evenodd"
      />
    </svg>
  );
}
export default SvgInductionLoop;
