// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgInductionLoopSquare(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 24 24"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      {...props}
    >
      <g clipPath="url(#a)">
        <path
          fill="currentColor"
          fillRule="evenodd"
          d="M0 4a4 4 0 0 1 4-4h16a4 4 0 0 1 4 4v16a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4zm10.137 5.96c0-1.081.838-1.961 1.867-1.961 1.03 0 1.868.88 1.868 1.96 0 .483.37.872.83.872s.83-.39.83-.871c0-2.043-1.582-3.704-3.527-3.704S8.477 7.916 8.477 9.96c0 .482.371.871.83.871.46 0 .83-.39.83-.871m-.324 2.404a.8.8 0 0 1 1.173 0 .9.9 0 0 1 0 1.233l-5.27 5.533a.8.8 0 0 1-.587.256.8.8 0 0 1-.586-.256.903.903 0 0 1 0-1.232zm10.8-10.108a.8.8 0 0 0-1.173 0l-1.836 1.927a.9.9 0 0 0 0 1.233c.162.17.374.255.587.255a.8.8 0 0 0 .587-.256l1.835-1.927a.9.9 0 0 0 0-1.232M6.471 10.67c-.459 0-.83-.39-.83-.872 0-3.684 2.855-6.681 6.364-6.681s6.362 2.997 6.362 6.681c0 2.05-.877 3.956-2.406 5.233l-1.242 1.06c-.399.363-.866 1.549-.866 2.568v.29c0 1.682-1.086 3.05-2.421 3.05h-1.093c-.459 0-.83-.39-.83-.872 0-.481.371-.87.83-.87h1.093c.358 0 .761-.56.761-1.308v-.29c0-1.47.627-3.148 1.46-3.905l1.268-1.082c1.138-.95 1.786-2.36 1.786-3.874 0-2.723-2.11-4.938-4.702-4.938C9.41 4.86 7.3 7.076 7.3 9.799c0 .482-.37.872-.83.872"
          className="icon__shape"
          clipRule="evenodd"
        />
      </g>
      <defs>
        <clipPath id="a">
          <path d="M0 0h24v24H0z" />
        </clipPath>
      </defs>
    </svg>
  );
}
export default SvgInductionLoopSquare;
