// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgInformation(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape" transform="translate(8 3)">
        <path d="M6.25 15.34H5V8.07a1 1 0 0 0-1-1H1.75a1 1 0 1 0 0 2H3v6.26H1.75a1 1 0 0 0 0 2h4.5a1 1 0 0 0 0-2z" />
        <circle cx={4} cy={2.79} r={2.13} />
      </g>
    </svg>
  );
}
export default SvgInformation;
