// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgInformation(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        transform="translate(8 3)"
      >
        <path d="M6.25 15.34H5V8.07a1 1 0 0 0-1-1H1.75a1 1 0 1 0 0 2H3v6.26H1.75a1 1 0 0 0 0 2h4.5a1 1 0 0 0 0-2v.01z" />
        <circle cx={4} cy={2.79} r={2.13} />
      </g>
    </svg>
  );
}
export default SvgInformation;
