// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgInfo2(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M22 7.75a10.45 10.45 0 0 0-2.33-3.5 10.6 10.6 0 0 0-7.76-3.18A10.27 10.27 0 0 0 4.3 4.23a10.9 10.9 0 0 0-2.4 3.56 10.85 10.85 0 0 0 0 8.28 10.8 10.8 0 0 0 2.38 3.52A10.9 10.9 0 0 0 7.8 22a10.6 10.6 0 0 0 4.12.82 10.8 10.8 0 0 0 4.17-.82 11.2 11.2 0 0 0 3.61-2.41 10 10 0 0 0 2.3-3.48c.53-1.33.8-2.749.79-4.18A11.1 11.1 0 0 0 22 7.75m-3.69 10.41a9.4 9.4 0 0 1-3 2 8.82 8.82 0 0 1-6.76 0 9.2 9.2 0 0 1-4.83-4.86 8.62 8.62 0 0 1 0-6.75 9.4 9.4 0 0 1 2-2.92A8.42 8.42 0 0 1 12 3a8.6 8.6 0 0 1 6.31 2.62 8.7 8.7 0 0 1 1.92 2.87 8.9 8.9 0 0 1 .66 3.42 8.35 8.35 0 0 1-2.58 6.25"
        className="icon__shape"
      />
      <path
        fill="currentColor"
        d="M14.056 16.733h-1.035v-5.871a.82.82 0 0 0-.829-.808h-1.864a.82.82 0 0 0-.828.808c0 .446.37.807.828.807h1.036v5.056h-1.036a.82.82 0 0 0-.828.808c0 .446.37.808.828.808h3.728a.82.82 0 0 0 .829-.808.82.82 0 0 0-.829-.808z"
        className="icon__shape"
      />
      <circle
        cx={11.75}
        cy={6.6}
        r={1.6}
        fill="currentColor"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgInfo2;
