// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgInfo2(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g>
        <path
          className="icon__shape"
          fill="currentColor"
          fillRule="nonzero"
          d="M22 7.75a10.45 10.45 0 0 0-2.33-3.5 10.6 10.6 0 0 0-7.76-3.18A10.27 10.27 0 0 0 4.3 4.23a10.91 10.91 0 0 0-2.4 3.56 10.85 10.85 0 0 0 0 8.28 10.83 10.83 0 0 0 2.38 3.52A10.93 10.93 0 0 0 7.8 22a10.57 10.57 0 0 0 4.12.82 10.82 10.82 0 0 0 4.17-.82 11.17 11.17 0 0 0 3.61-2.41 10 10 0 0 0 2.3-3.48c.53-1.33.8-2.749.79-4.18A11.06 11.06 0 0 0 22 7.75zm-3.69 10.41a9.37 9.37 0 0 1-3 2 8.82 8.82 0 0 1-6.76 0 9.2 9.2 0 0 1-4.83-4.86 8.62 8.62 0 0 1 0-6.75 9.35 9.35 0 0 1 2-2.92A8.42 8.42 0 0 1 12 3a8.6 8.6 0 0 1 6.31 2.62 8.69 8.69 0 0 1 1.92 2.87 8.93 8.93 0 0 1 .66 3.42 8.35 8.35 0 0 1-2.58 6.25z"
        />
        <path
          className="icon__shape"
          fill="currentColor"
          fillRule="nonzero"
          d="M14.056 16.733h-1.035v-5.871a.818.818 0 0 0-.829-.808h-1.864a.818.818 0 0 0-.828.808c0 .446.37.807.828.807h1.036v5.056h-1.036a.818.818 0 0 0-.828.808c0 .446.37.808.828.808h3.728a.818.818 0 0 0 .829-.808.818.818 0 0 0-.829-.808v.008z"
        />
        <circle
          cx={11.75}
          cy={6.6}
          r={1.6}
          className="icon__shape"
          fill="currentColor"
          fillRule="nonzero"
        />
      </g>
    </svg>
  );
}
export default SvgInfo2;
