// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgInvertColours(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M12 2c.3 0 .6.1.8.3C16.7 6.8 19 10 19 13.4a7 7 0 1 1-14 0C5 10 7.3 6.8 11.2 2.3A1 1 0 0 1 12 2m0 3.2c-3 3.7-4.8 6.3-4.8 8.2a4.8 4.8 0 1 0 9.6 0c0-1.9-1.8-4.5-4.8-8.2m0-.2v14h-.1c-2.6-.1-4.8-2.3-4.8-5 0-1.6 1.5-3.9 4.9-8.1z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgInvertColours;
