// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgJournal(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        d="M16.08 1.33H10a3 3 0 0 0-3 3V5h-.67a3 3 0 0 0-3 3v11.67a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V19H18a3 3 0 0 0 3-3V6.25zM19 7.08v.59h-2.33a1 1 0 0 1-1-1V3.75zm-3.67 12.59a1 1 0 0 1-1 1h-8a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1H7v9a3 3 0 0 0 3 3h5.33zM18 17h-8a1 1 0 0 1-1-1V4.33a1 1 0 0 1 1-1h3.67v3.34a3 3 0 0 0 3 3H19V16a1 1 0 0 1-1 1z"
      />
    </svg>
  );
}
export default SvgJournal;
