// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgLikes(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M22.71 9a6 6 0 0 0-10.28-4.29l-.49.49-.49-.49a6.025 6.025 0 0 0-8.52 8.52l8.31 8.31a1 1 0 0 0 1.41 0 1 1 0 0 0 .07-.11l8.28-8.2A6 6 0 0 0 22.71 9m-3.17 2.85-7.6 7.6-7.6-7.6A4.027 4.027 0 0 1 10 6.12l1.2 1.2a1 1 0 0 0 1.41 0l1.2-1.2a4.023 4.023 0 0 1 5.69 5.69z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgLikes;
