// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgLink(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M8.12 16.76a2.556 2.556 0 1 1-3.62-3.61L8.75 8.9a2.56 2.56 0 0 1 3.61 3.61 1 1 0 0 0 1.41 1.41 4.56 4.56 0 0 0-6.43-6.44l-4.25 4.25a4.554 4.554 0 0 0 6.44 6.44 1 1 0 0 0-1.41-1.41M20.84 5.45a4.56 4.56 0 0 0-6.44 0 1 1 0 0 0 1.41 1.41 2.553 2.553 0 0 1 3.61 3.61l-4.25 4.25a2.63 2.63 0 0 1-3.61 0 2.56 2.56 0 0 1 0-3.61 1 1 0 0 0-1.41-1.41 4.554 4.554 0 0 0 6.44 6.44l4.25-4.25a4.56 4.56 0 0 0 0-6.44"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgLink;
