// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgListView(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape" transform="translate(2 3)">
        <path d="M7 3.53h12a1 1 0 0 0 0-2H7a1 1 0 1 0 0 2m12 5H7a1 1 0 1 0 0 2h12a1 1 0 0 0 0-2m0 7H7a1 1 0 0 0 0 2h12a1 1 0 0 0 0-2" />
        <circle cx={2.01} cy={16.53} r={2} />
        <circle cx={2.01} cy={9.53} r={2} />
        <circle cx={2.01} cy={2.53} r={2} />
      </g>
    </svg>
  );
}
export default SvgListView;
