// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgMessage(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape">
        <path d="M5.47 6.71h13v1.63h-13zm0 6.5h13v1.63h-13zm0-3.25h13v1.63h-13z" />
        <path d="M19.47 3.34h-15a3.16 3.16 0 0 0-3 3v9a3.16 3.16 0 0 0 3 3v3a1 1 0 0 0 1.7.66l3.71-3.71h9.59a3.16 3.16 0 0 0 3-3v-9a3.16 3.16 0 0 0-3-2.95m1 12a1.17 1.17 0 0 1-1 1h-10a1 1 0 0 0-.71.29l-2.29 2.3v-1.59a1 1 0 0 0-1-1h-1a1.17 1.17 0 0 1-1-1v-9a1.17 1.17 0 0 1 1-1h15c.52.071.929.48 1 1z" />
      </g>
    </svg>
  );
}
export default SvgMessage;
