// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgMinimise(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M10.02 13.001q.027 0 .053.002l.03.002.028.004.017.002.066.012q.02.004.04.01l.047.013.034.012.058.022.021.01.052.026.016.007.052.032.016.01.024.018.055.04.016.014q.027.022.051.046l.011.01.009.01q.056.058.103.124l.017.025q.014.021.026.043l.017.029.03.058.011.029a1 1 0 0 1 .072.272q.002.018.003.037.003.03.004.06L11 14v6a1 1 0 0 1-2 0v-3.586l-5.293 5.293a1 1 0 0 1-1.414-1.414L7.586 15H4a1 1 0 0 1 0-2h6zM20.37 2.225a1 1 0 0 1 1.406 1.406l-.069.076L16.414 9H20a1 1 0 0 1 0 2h-6a1 1 0 0 1-.197-.02l-.034-.008-.062-.016-.04-.014-.052-.02-.026-.012a1.005 1.005 0 0 1-.546-.62l-.013-.05A1 1 0 0 1 13 10V4a1 1 0 1 1 2 0v3.586l5.293-5.293z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgMinimise;
