// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgMinimise(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M9.37 13.225a1 1 0 0 1 1.405 1.406l-.068.076L5.414 20H9a1 1 0 1 1 0 2H3q-.085-.001-.166-.016-.015-.001-.031-.005l-.034-.007-.062-.016a1 1 0 0 1-.257-.121 1 1 0 0 1-.33-.36l-.02-.042a1 1 0 0 1-.057-.141A1.003 1.003 0 0 1 2 21v-6a1 1 0 1 1 2 0v3.586l5.293-5.293zM21.02 2.001q.027 0 .053.002l.03.002q.196.021.363.11l.015.008.053.031.016.011.024.018q.028.018.055.04l.015.013q.028.023.052.047l.011.01.009.01q.055.057.102.124l.018.025q.015.021.026.043l.017.028.031.064.01.023.021.058.011.032.017.057.006.023a1 1 0 0 1 .017.103q.002.018.003.037.004.03.004.06L22 3v6a1 1 0 1 1-2 0V5.414l-5.293 5.293a1 1 0 1 1-1.414-1.414L18.586 4H15a1 1 0 1 1 0-2h6z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgMinimise;
