// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgMinus(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M20.49 11h-17a1 1 0 1 0 0 2h17a1 1 0 0 0 0-2"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgMinus;
