// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgMusic(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        d="M21 2H9a1 1 0 0 0-1 1v11.54A4 4 0 1 0 10 18V4h10v6.54A4 4 0 1 0 22 14V3a1 1 0 0 0-1-1zM6 20a2 2 0 1 1 2-2 2 2 0 0 1-2 2zm12-4a2 2 0 1 1 2-2 2 2 0 0 1-2 2z"
      />
    </svg>
  );
}
export default SvgMusic;
