// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgMute(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M8.3 4.73a1 1 0 0 0-1.12.4L5.46 7.71H3a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h2.46l1.72 2.54a1 1 0 0 0 .83.44 1 1 0 0 0 .29 0 1 1 0 0 0 .71-1v-13a1 1 0 0 0-.71-.96zM7 15.43l-.19-.29a1 1 0 0 0-.81-.43H4v-5h2a1 1 0 0 0 .83-.44L7 9v6.43zm10.26-3.24l3.61-3.61a1 1 0 0 0-1.41-1.41l-3.61 3.61-3.61-3.61a1 1 0 0 0-1.41 1.41l3.61 3.61-3.62 3.61a1 1 0 1 0 1.41 1.41l3.61-3.61 3.61 3.61a1 1 0 0 0 1.41-1.41l-3.6-3.61z"
      />
    </svg>
  );
}
export default SvgMute;
