// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgOpenFolder(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M2.23 20.93c-.61 0-1.14-.22-1.58-.66s-.66-.96-.66-1.58V5.3c0-.61.22-1.14.66-1.58s.96-.66 1.58-.66h6.7l2.23 2.23h8.93c.61 0 1.14.22 1.58.66s.66.96.66 1.58H2.23v11.16l2.68-8.93H24l-2.87 9.57c-.15.48-.42.87-.82 1.16s-.84.43-1.33.43H2.23Z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgOpenFolder;
