// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgOpenFolder(props: SVGProps<SVGSVGElement>) {
  return (
    <svg fill="none" viewBox="0 0 24 24" {...props}>
      <mask
        id="a"
        width={24}
        height={24}
        x={0}
        y={0}
        maskUnits="userSpaceOnUse"
        style={{
          maskType: 'alpha',
        }}
      >
        <path fill="currentColor" d="M0 .5h24v24H0z" />
      </mask>
      <g mask="url(#a)">
        <path
          fill="currentColor"
          d="M2.666 13.833q-.55 0-.941-.391a1.28 1.28 0 0 1-.392-.942v-8q0-.55.392-.942.391-.39.941-.391h4L8 4.5h5.333q.55 0 .942.392.39.391.391.941h-12V12.5l1.6-5.333h11.4l-1.716 5.716a1.3 1.3 0 0 1-.492.692 1.32 1.32 0 0 1-.792.258z"
          className="icon__shape"
        />
      </g>
    </svg>
  );
}
export default SvgOpenFolder;
