// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgPause(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M19.4 3.6H16c-.6 0-1 .4-1 1V19c0 .6.4 1 1 1h3.4c.6 0 1-.4 1-1V4.6c0-.5-.4-1-1-1M8.5 3.6H5.1c-.6 0-1 .4-1 1V19c0 .6.4 1 1 1h3.4c.6 0 1-.4 1-1V4.6c0-.5-.4-1-1-1"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgPause;
