// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { IconSvg } from '../types';

const SvgPhone: IconSvg = props => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path
      className="icon__shape"
      fill="currentColor"
      fillRule="nonzero"
      d="m19.41,21.42c.14-.11.25-.26.3-.44.08-.23.06-.48-.05-.7-.63-1.25-1.95-3.36-3.77-3.55,0,0,0,0-.01,0h-.02s-.02,0-.03,0c0,0,0,0,0,0,0,0,0,0-.01,0-.66.18-1.3.42-1.91.73-1.82.11-3.42-1.96-4.21-3.21-1.21-1.85-1.67-4.09-1.26-6.27.03-.15.06-.29.1-.43.93-.48,1.98-1.37,1.92-2.89-.04-1.06-.55-2.12-1.53-3.16-.14-.15-.32-.25-.52-.3-.2-.04-.41-.02-.6.06-.22.09-.43.19-.63.28,0,0,0,0,0,0-1.32.64-2.17,1.33-2.52,2.06-.87,1.8-1.4,7.27,2.51,12.71,3.21,4.47,6.57,6.59,9.97,6.3.56-.05,1.31-.44,2.31-1.22h0Z"
    />
  </svg>
);

export default SvgPhone;
