// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgPlay(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M20 12.8c1.2-.6 1.2-1.5 0-2L5.3 3.9c-.7-.5-1.6-.3-2 .3-.2.3-.3.7-.2 1v13.1c-.1.8.4 1.5 1.2 1.7.3.1.7 0 1-.2z"
      />
    </svg>
  );
}
export default SvgPlay;
