// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgRequest(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g className="icon__shape" fill="currentColor" fillRule="nonzero">
        <path d="M7.79 14.5a1 1 0 0 0 1.56 0l4-5a1 1 0 0 0-1.56-1.25L9.57 11V7.87a3 3 0 0 1 3-3h7a1 1 0 0 0 0-2h-7a5 5 0 0 0-5 5V11L5.35 8.25A1 1 0 1 0 3.79 9.5l4 5z" />
        <path d="M22.13 15l-6-4a1 1 0 0 0-1.26.13l-2 2a1 1 0 0 0 0 1.41l2 2-.64.32-4.58.92-4.71-1.83a1 1 0 0 0-1.27.48l-1 2a1 1 0 0 0 .38 1.3l5 3a1 1 0 0 0 .51.14h13a1 1 0 0 0 1-1v-6a1 1 0 0 0-.43-.87zm-1.55 5.83H8.85l-4-2.38.17-.35 4.18 1.7a1 1 0 0 0 .57.05l5-1a1 1 0 0 0 .25-.09l2-1a1 1 0 0 0 .26-1.6L15 13.87l.71-.71 4.87 3.25v4.42z" />
      </g>
    </svg>
  );
}
export default SvgRequest;
