// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgRotateLeft(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M11.9 2.31a9.6 9.6 0 0 0-7 3V3.67a1 1 0 1 0-2 0v4.08a1 1 0 0 0 1 1H8a1 1 0 1 0 0-2H6.3a7.61 7.61 0 0 1 5.6-2.43 7.69 7.69 0 1 1-7.56 9.08 1.016 1.016 0 0 0-2 .36A9.69 9.69 0 1 0 11.9 2.31z"
      />
    </svg>
  );
}
export default SvgRotateLeft;
