// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgRotate360(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M12.72 6.52l-1.93-1.93A1 1 0 0 0 9.38 6l.28.28c-5.5.5-9.42 2.79-9.42 5.71 0 2.61 3.16 4.78 8.06 5.54h.15a1.003 1.003 0 0 0 .15-2c-4.13-.6-6.36-2.28-6.36-3.53 0-1.53 3-3.2 7.26-3.68l-.12.12a1 1 0 1 0 1.41 1.41l1.93-1.93a1 1 0 0 0 0-1.4zM23.63 12c0-2.65-3.23-4.83-8.22-5.57a1.01 1.01 0 0 0-.29 2c4.23.62 6.52 2.31 6.52 3.59 0 1.5-2.89 3.15-7.08 3.66l1-1a1 1 0 1 0-1.41-1.41L11.37 16a1 1 0 0 0 0 1.6l2.79 2.79A1 1 0 1 0 15.57 19l-1.28-1.28c5.46-.52 9.34-2.8 9.34-5.72z"
      />
    </svg>
  );
}
export default SvgRotate360;
