// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgSaveTo(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M18.9 2.23h-14a3 3 0 0 0-3 3v14a3 3 0 0 0 3 3h14a3 3 0 0 0 3-3v-14a3 3 0 0 0-3-3zm-7 2v1a1 1 0 0 0 2 0v-1h1v3h-6v-3h3zm-4 16v-6h8v6h-8zm12-1a1 1 0 0 1-1 1h-1v-6.36a1.64 1.64 0 0 0-1.64-1.64H7.51a1.64 1.64 0 0 0-1.64 1.64v6.36h-1a1 1 0 0 1-1-1v-14a1 1 0 0 1 1-1h2V8a1.25 1.25 0 0 0 1.25 1.25h7.49A1.25 1.25 0 0 0 16.87 8V4.23h2a1 1 0 0 1 1 1l.03 14z"
      />
    </svg>
  );
}
export default SvgSaveTo;
