// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgSearch(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="m22.6 20.59-6.25-6.25a7.53 7.53 0 1 0-1.41 1.41L21.19 22a1 1 0 0 0 1.41-1.41M4.9 9.8a5.5 5.5 0 1 1 5.5 5.5 5.51 5.51 0 0 1-5.5-5.5"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgSearch;
