// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgShare(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g className="icon__shape" fill="currentColor" fillRule="nonzero">
        <path d="M10 18a1 1 0 0 0 1-1v-7a3 3 0 0 1 3-3h3.1l-1.6 1.2a1 1 0 1 0 1.2 1.6l4-3a1 1 0 0 0 0-1.6l-4-3a1 1 0 1 0-1.2 1.6L17.1 5H14a5 5 0 0 0-5 5v7a1 1 0 0 0 1 1z" />
        <path d="M20.2 10.2a1 1 0 0 0-1 1V19a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V6.89a1 1 0 0 1 1-1h2.6a1 1 0 1 0 0-2H5a3 3 0 0 0-3 3V19a3 3 0 0 0 3 3h13.2a3 3 0 0 0 3-3v-7.8a1 1 0 0 0-1-1z" />
      </g>
    </svg>
  );
}
export default SvgShare;
