// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgSinglePage(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M8.7 7.3h6.7v2H8.7zM8.7 10.7h6.7v2H8.7zM8.7 14h6.7v2H8.7z"
        className="icon__shape"
      />
      <path
        fill="currentColor"
        d="M15.7 3.3H8.3c-1.7 0-3 1.3-3 3v11.3c0 1.7 1.3 3 3 3h7.3c1.7 0 3-1.3 3-3V6.3c.1-1.6-1.3-3-2.9-3m1 14.4c0 .6-.4 1-1 1H8.3c-.6 0-1-.4-1-1V6.3c0-.6.4-1 1-1h7.3c.6 0 1 .4 1 1v11.4z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgSinglePage;
