// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgSmartphone(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape" transform="translate(5 1)">
        <path d="M10 .69H4.38a4 4 0 0 0-4 4v13.09a4 4 0 0 0 4 4H10a4 4 0 0 0 4-4V4.67a4 4 0 0 0-4-3.98M2.39 6.75H12v6.57H2.39zm2-4.06H10a2 2 0 0 1 2 2v.08H2.39v-.1a2 2 0 0 1 1.99-1.98zM10 19.77H4.38a2 2 0 0 1-2-2v-2.45H12v2.47a2 2 0 0 1-2 1.98" />
        <circle cx={7.2} cy={17.41} r={1.25} />
      </g>
    </svg>
  );
}
export default SvgSmartphone;
