// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgSpeechToText(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M22.062 10.523h-1.754v4.615h-1.293v-4.615h-1.661V9.508h4.708zm-6.831 1.662 1.938 2.953h-1.477l-1.2-1.938-1.292 1.938h-1.385l2.031-2.953L12 9.508h1.477l1.108 1.846 1.2-1.846h1.384zm-3.785 2.953H7.108V9.415h4.246v1.016H8.4v1.2h2.77v1.015H8.4v1.385h3.046zm-4.8-4.615H4.892v4.615h-1.2v-4.615H1.938V9.508h4.708zM24 20.677V3.323A3.31 3.31 0 0 0 20.677 0H3.323A3.31 3.31 0 0 0 0 3.323v17.354A3.31 3.31 0 0 0 3.323 24h17.354A3.31 3.31 0 0 0 24 20.677"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgSpeechToText;
