// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgThreeD(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="m21.5 5.94-9-5.2a1 1 0 0 0-1 0l-9 5.2a1 1 0 0 0-.5.86v10.4a1 1 0 0 0 .5.87l9 5.2a1 1 0 0 0 1 0l9-5.2a1 1 0 0 0 .5-.87V6.8a1 1 0 0 0-.5-.86M20 14.1 13.87 3.84 20 7.38zm-.93 2.34H4.93L12 4.62zm-8.94-12.6L4 14.1V7.38zM12 21.24l-4.84-2.8h9.68z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgThreeD;
