// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgTickCircle(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M24 12c0 6.627-5.373 12-12 12S0 18.627 0 12 5.373 0 12 0s12 5.373 12 12m-2 0c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2s10 4.477 10 10M9.971 15.636c.24.234.559.364.898.364.34 0 .658-.13.898-.364l.035-.034 4.915-5.68a1.15 1.15 0 0 0-.138-1.645 1.21 1.21 0 0 0-1.679.135l-4.098 4.736-1.769-1.733a1.207 1.207 0 0 0-1.685 0 1.15 1.15 0 0 0 0 1.65z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgTickCircle;
