// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgTickCircle(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="evenodd"
        d="M24 12C24 18.6274 18.6274 24 12 24C5.37258 24 0 18.6274 0 12C0 5.37258 5.37258 0 12 0C18.6274 0 24 5.37258 24 12ZM22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12ZM9.971 15.636C10.211 15.87 10.53 16 10.869 16C11.209 16 11.527 15.87 11.767 15.636L11.802 15.602L16.717 9.92196C17.142 9.43096 17.081 8.69396 16.579 8.27696C16.078 7.85996 15.326 7.92096 14.9 8.41196L10.802 13.148L9.033 11.415C8.568 10.958 7.813 10.958 7.348 11.415C6.884 11.87 6.884 12.609 7.348 13.065L9.971 15.636Z"
      />
    </svg>
  );
}
export default SvgTickCircle;
