// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgTicketSoldOut(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M9.45 10a1.13 1.13 0 1 0 .018-2.26A1.13 1.13 0 0 0 9.45 10zM14 10a1.13 1.13 0 1 0 .02-2.26A1.13 1.13 0 0 0 14 10zm-2.3 1.16a4.9 4.9 0 0 0-4 2.13 1 1 0 1 0 1.65 1.13 2.89 2.89 0 0 1 4.77 0 1 1 0 0 0 1.65-1.13 4.9 4.9 0 0 0-4.07-2.13zm11.81-.89l-2.6-2.6a1 1 0 0 0-1-.25 2.81 2.81 0 0 1-3.51-3.51 1 1 0 0 0-.25-1l-2.6-2.6a1 1 0 0 0-1.41 0L.32 12.16a1 1 0 0 0 0 1.41l2.6 2.6a1 1 0 0 0 1 .25 2.81 2.81 0 0 1 3.51 3.51 1 1 0 0 0 .25 1l2.6 2.6a1 1 0 0 0 1.41 0l11.82-11.84a1 1 0 0 0 0-1.42zM11 21.4l-1.5-1.5a4.8 4.8 0 0 0-5.52-5.52l-1.5-1.5L12.86 2.45 14.36 4a4.8 4.8 0 0 0 5.52 5.52l1.5 1.5L11 21.4z"
      />
    </svg>
  );
}
export default SvgTicketSoldOut;
