// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgTiktok(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path d="M18.33 6.03a4.72 4.72 0 0 1-2.14-3.95h-3.38v13.55a2.85 2.85 0 0 1-2.84 2.74 2.85 2.85 0 0 1-2.84-2.85c0-1.57 1.28-2.84 2.84-2.84.29 0 .57.05.84.13V9.36q-.405-.06-.84-.06c-3.43 0-6.23 2.79-6.23 6.23 0 2.11 1.05 3.97 2.66 5.1 1.01.71 2.24 1.13 3.57 1.13 3.43 0 6.23-2.79 6.23-6.23V8.66c1.33.95 2.95 1.51 4.71 1.51V6.79c-.94 0-1.82-.28-2.56-.76Z" />
    </svg>
  );
}
export default SvgTiktok;
