// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgTree(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M21 18.58V15.3a3 3 0 0 0-3-3h-5v-2.14a4 4 0 1 0-2 0v2.14H6a3 3 0 0 0-3 3v3.28a2 2 0 1 0 2 0V15.3a1 1 0 0 1 1-1h5v4.28a2 2 0 1 0 2 0V14.3h5a1 1 0 0 1 1 1v3.28a2 2 0 1 0 2 0M10 6.3a2 2 0 1 1 4 0 2 2 0 0 1-4 0"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgTree;
