// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgTripadvisor(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape" transform="translate(0 5)">
        <circle cx={6.489} cy={7.911} r={1} />
        <circle cx={17.991} cy={7.893} r={1} />
        <path d="M6.631 5.129a2.773 2.773 0 1 0 0 5.547 2.773 2.773 0 0 0 0-5.547m0 4.702a1.92 1.92 0 1 1 0-3.84 1.92 1.92 0 0 1 0 3.84" />
        <path d="M23.902 2.284H20.08A13.76 13.76 0 0 0 12.444.151a14.4 14.4 0 0 0-7.848 2.133H.889A5.3 5.3 0 0 1 2.036 4.57a5.737 5.737 0 1 0 9.102 6.987q.721.838 1.306 1.777s.818-1.226 1.28-1.777a5.718 5.718 0 0 0 9.067-6.97 5.3 5.3 0 0 1 1.111-2.302zM6.693 12.524a4.604 4.604 0 1 1 0-9.208 4.604 4.604 0 0 1 0 9.208m0-10.32a14.65 14.65 0 0 1 5.751-1.102c1.894-.016 3.77.36 5.512 1.102a5.716 5.716 0 0 0-5.512 5.716 5.716 5.716 0 0 0-5.742-5.716zm11.44 10.32a4.604 4.604 0 1 1 0-9.208 4.604 4.604 0 0 1 0 9.208" />
        <path d="M18.133 5.12a2.773 2.773 0 1 0 0 5.547 2.773 2.773 0 0 0 0-5.547m0 4.702a1.92 1.92 0 1 1 1.92-1.92 1.92 1.92 0 0 1-1.92 1.876z" />
      </g>
    </svg>
  );
}
export default SvgTripadvisor;
