// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgTumblr(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M15.86 18.6a1.76 1.76 0 0 1-2-2v-5.87h3.81V7.31H13.9V2.26h-3a.15.15 0 0 0-.14.14 6.08 6.08 0 0 1-4 5.37v2.92h2.33v6.19c0 2.24 1.39 5.41 5.84 5.34 1.49 0 3.17-.64 3.52-1.17l-1-2.85a4.1 4.1 0 0 1-1.59.4"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgTumblr;
