// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgTwitter(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M23.39 6.06a9 9 0 0 1-2.6.71 4.54 4.54 0 0 0 2-2.5 9 9 0 0 1-2.87 1.1 4.53 4.53 0 0 0-7.71 4.13 12.85 12.85 0 0 1-9.35-4.73 4.53 4.53 0 0 0 1.4 6 4.5 4.5 0 0 1-2-.57v.06a4.53 4.53 0 0 0 3.63 4.44 4.5 4.5 0 0 1-2 .08A4.53 4.53 0 0 0 8 18a9.08 9.08 0 0 1-5.62 1.94 9 9 0 0 1-1.08-.06 12.8 12.8 0 0 0 6.94 2A12.79 12.79 0 0 0 21.14 9v-.59a9.2 9.2 0 0 0 2.25-2.35"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgTwitter;
