// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgUnavailable(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M12.06 9.63 4.238 6.139Q4.8 5.32 5.442 4.682q2.562-2.62 6.268-2.62 3.708 0 6.288 2.62 2.6 2.562 2.6 6.307 0 1.184-.271 2.329zm-.35 10.228q-3.63 0-6.288-2.62-2.64-2.637-2.64-6.25 0-1.59.487-2.93l5.55 2.485 10.712 4.755q-.543.99-1.494 1.902-2.658 2.659-6.327 2.658M11.672.12q-4.503 0-7.646 3.145Q.823 6.526.823 10.989q0 4.445 3.203 7.647 3.22 3.22 7.646 3.22 4.482 0 7.782-3.24 3.105-3.046 3.105-7.627t-3.163-7.723Q16.252.12 11.672.12"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgUnavailable;
