// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgVideo(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape">
        <path d="M19.5 4.3h-15a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h15a3 3 0 0 0 3-3v-10a3 3 0 0 0-3-3m1 13a1 1 0 0 1-1 1h-15a1 1 0 0 1-1-1v-10a1 1 0 0 1 1-1h15a1 1 0 0 1 1 1z" />
        <path d="m15.22 11.19-4.28-2.45A1.42 1.42 0 0 0 8.8 10v4.9a1.43 1.43 0 0 0 2.13 1.24l4.29-2.45a1.43 1.43 0 0 0 0-2.48zm-4.42 2.7V11l2.56 1.46z" />
      </g>
    </svg>
  );
}
export default SvgVideo;
