// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgVolume(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape">
        <path d="M8.3 5.73a1 1 0 0 0-1.12.4L5.46 8.71H3a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h2.46l1.72 2.54a1 1 0 0 0 .83.44 1 1 0 0 0 .29 0 1 1 0 0 0 .71-1v-13a1 1 0 0 0-.71-.96M7 16.43l-.19-.29a1 1 0 0 0-.81-.43H4v-5h2a1 1 0 0 0 .83-.44L7 10zm8.55-9.48a1 1 0 1 0-1.39 1.44 6 6 0 0 1 0 8.64 1 1 0 0 0 1.38 1.45 8 8 0 0 0 0-11.53z" />
        <path d="M11.49 9.22a1 1 0 1 0-.88 1.78 1.87 1.87 0 0 1 0 3.38A1 1 0 0 0 11 16.3a1 1 0 0 0 .43-.1 3.87 3.87 0 0 0 .06-7zm7.94-3.93a1 1 0 0 0-1.57 1.23 10 10 0 0 1 0 12.37 1 1 0 1 0 1.57 1.24 12 12 0 0 0 0-14.84" />
      </g>
    </svg>
  );
}
export default SvgVolume;
