// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgWellcome(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 68 68" {...props}>
      <path
        fill="currentColor"
        d="M72.3-.1H-5v76.8h79.2V-.1zM46.8 49.2s-3.5-1-6.6-1.9c-2.3-.7-3.6-1.9-4.1-3.9-.4-1.3-1.3-4.7-2.5-9.3l-4 15.1s-4.6-1.4-6.9-2c-2.2-.6-3.3-2.1-3.9-4.2-.9-3.3-5.8-22-5.8-22l8.9-1 4 15.1 4-15.1H34c2.2 0 3.6 1 4.3 3.3.2.9 1.6 6.1 3.1 11.8l4-15.1 8.9 1z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgWellcome;
