// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgWellcome(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M23.78 0H-.37v24h24.75V0h-.59Zm-7.97 16.56s-1.09-.31-2.06-.59c-.72-.22-1.12-.59-1.28-1.22-.13-.41-.41-1.47-.78-2.91l-1.25 4.72s-1.44-.44-2.16-.62c-.69-.19-1.03-.66-1.22-1.31-.28-1.03-1.81-6.87-1.81-6.87l2.78-.31 1.25 4.72 1.25-4.72h1.28c.69 0 1.12.31 1.34 1.03.06.28.5 1.91.97 3.69l1.25-4.72 2.78.31-2.34 8.81Z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgWellcome;
