// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgWellcome(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 68 68" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        d="M72.3-0.1h-0.2H61.8h-1.8H7.4H-4.8H-5v65.3v11.5h0.3H7.4h54.4h10.2h2.2V65.2V-0.1H72.3z M46.8,49.2c0,0-3.5-1-6.6-1.9 c-2.3-0.7-3.6-1.9-4.1-3.9c-0.4-1.3-1.3-4.7-2.5-9.3l-4,15.1c0,0-4.6-1.4-6.9-2c-2.2-0.6-3.3-2.1-3.9-4.2c-0.9-3.3-5.8-22-5.8-22 l8.9-1l4,15.1l4-15.1H34c2.2,0,3.6,1,4.3,3.3c0.2,0.9,1.6,6.1,3.1,11.8l4-15.1l8.9,1L46.8,49.2z"
      />
    </svg>
  );
}
export default SvgWellcome;
