// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgWifi(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        transform="translate(3 3)"
      >
        <circle cx={2.06} cy={16.09} r={1.94} />
        <path d="M2.06 9.39a1 1 0 1 0 0 2 4.7 4.7 0 0 1 4.69 4.69 1 1 0 0 0 2 0 6.7 6.7 0 0 0-6.69-6.69z" />
        <path d="M2.06 4.71a1 1 0 1 0 0 2 9.38 9.38 0 0 1 9.37 9.37 1 1 0 1 0 2 0C13.419 9.805 8.335 4.721 2.06 4.71z" />
        <path d="M2.06 0a1 1 0 1 0 0 2 14.07 14.07 0 0 1 14.05 14.09 1 1 0 0 0 2 0C18.116 7.217 10.933.017 2.06 0z" />
      </g>
    </svg>
  );
}
export default SvgWifi;
