// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgXSocial(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="m13.66 10.63 6.51-7.56h-1.54l-5.65 6.57-4.51-6.57H3.26L10.08 13l-6.82 7.93H4.8l5.97-6.94 4.77 6.94h5.21l-7.08-10.3Zm-2.11 2.46-.69-.99-5.5-7.87h2.37l4.44 6.35.69.99 5.77 8.26h-2.37z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgXSocial;
