// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgYoutube(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M21.85 7.58A4.5 4.5 0 0 0 21 5.51a3 3 0 0 0-2.09-.88c-2.92-.21-7.29-.21-7.29-.21s-4.38 0-7.29.21a3 3 0 0 0-2.09.88 4.5 4.5 0 0 0-.83 2.07 32 32 0 0 0-.2 3.42v1.58q.015 1.69.21 3.37A4.5 4.5 0 0 0 2.25 18a3.53 3.53 0 0 0 2.3.89c1.67.16 7.09.21 7.09.21s4.38 0 7.3-.22A3 3 0 0 0 21 18a4.5 4.5 0 0 0 .83-2.07q.195-1.68.21-3.37V11a32 32 0 0 0-.19-3.42M9.48 14.45V8.59l5.63 2.94z"
        className="icon__shape"
      />
    </svg>
  );
}
export default SvgYoutube;
