// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgYoutube(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <path
        className="icon__shape"
        fill="currentColor"
        fillRule="nonzero"
        d="M21.85 7.58A4.51 4.51 0 0 0 21 5.51a3 3 0 0 0-2.09-.88c-2.92-.21-7.29-.21-7.29-.21s-4.38 0-7.29.21a3 3 0 0 0-2.09.88 4.51 4.51 0 0 0-.83 2.07 31.52 31.52 0 0 0-.2 3.42v1.58c.01 1.126.08 2.251.21 3.37A4.51 4.51 0 0 0 2.25 18a3.53 3.53 0 0 0 2.3.89c1.67.16 7.09.21 7.09.21s4.38 0 7.3-.22A3 3 0 0 0 21 18a4.51 4.51 0 0 0 .83-2.07c.13-1.119.2-2.244.21-3.37V11a31.57 31.57 0 0 0-.19-3.42zM9.48 14.45V8.59l5.63 2.94-5.63 2.92z"
      />
    </svg>
  );
}
export default SvgYoutube;
