// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn run-svgr"
import { SVGProps } from 'react';
function SvgZoomOut(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
      <g className="icon__shape" fill="currentColor" fillRule="nonzero">
        <path d="M21.15 19.71L17 15.61A8 8 0 1 0 15.63 17l4.1 4.1a1 1 0 0 0 1.41-1.41l.01.02zm-10.39-3a6 6 0 1 1 0-12 6 6 0 0 1 0 12z" />
        <path d="M13.93 9.74H7.78a1 1 0 1 0 0 2h6.15a1 1 0 0 0 0-2z" />
      </g>
    </svg>
  );
}
export default SvgZoomOut;
