// This is autogenerated from an SVG file
// Do not edit this file directly; edit the SVG file and run "yarn compile"
import { SVGProps } from 'react';
function SvgZoomOut(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" className="icon__shape">
        <path d="M21.15 19.71 17 15.61A8 8 0 1 0 15.63 17l4.1 4.1a1 1 0 0 0 1.41-1.41zm-10.39-3a6 6 0 1 1 0-12 6 6 0 0 1 0 12" />
        <path d="M13.93 9.74H7.78a1 1 0 1 0 0 2h6.15a1 1 0 0 0 0-2" />
      </g>
    </svg>
  );
}
export default SvgZoomOut;
