name: Bundle size
on: [pull_request]
jobs:
  diff:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          build-script: "build-webapps"
          clean-script: "clean"
          pattern: "**/webapp/.next/static/chunks/**/*.js"
          strip-hash: "\\b[-\\.](\\w{20})\\.js$"
