name: 'Chromatic'
# We get one Storybook per branch at https://<branch>--<appid>.chromatic.com
# https://www.chromatic.com/docs/permalinks
on:
  push:
    paths-ignore:
      - '.buildkite/**'
      - 'assets/**'
      - 'cache/**'
      - 'content/terraform/**'
      - 'docs/**'
      - 'identity/terraform/**'
      - 'infrastructure/**'
      - 'playwright/**'
      - 'prismic-model/**'
      - 'preview/**'

permissions:
  contents: read

jobs:
  chromatic-deployment:
    runs-on: default_x64_latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # https://github.com/actions/setup-node?tab=readme-ov-file#usage
      # The node-version input is optional. If not supplied, the node version from PATH will be used.
      # However, it is recommended to always specify Node.js version and don't rely on the system one.
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v12
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          workingDir: cardigan
          buildScriptName: build
          storybookBaseDir: cardigan
