name: 'Chromatic'
# We get one Storybook per branch at https://<branch>--<appid>.chromatic.com
# https://www.chromatic.com/docs/permalinks
on:
  push:
    paths-ignore:
      - '.buildkite/**'
      - 'assets/**'
      - 'cache/**'
      - 'content/terraform/**'
      - 'docs/**'
      - 'identity/terraform/**'
      - 'infrastructure/**'
      - 'playwright/**'
      - 'prismic-model/**'
      - 'preview/**'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          workingDir: cardigan
          buildScriptName: build
          storybookBaseDir: cardigan
