name: 'Chromatic'
# We get one Storybook per branch at https://<branch>--<appid>.chromatic.com
# https://www.chromatic.com/docs/permalinks
on:
  push:
    paths-ignore:
      - '.buildkite/**'
      - 'assets/**'
      - 'cache/**'
      - 'catalogue/terraform/**'
      - 'content/terraform/**'
      - 'docs/**'
      - 'identity/terraform/**'
      - 'infrastructure/**'
      - 'playwright/**'
      - 'prismic-model/**'
      - 'preview/**'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - run: "Hello world!"