name: Dependabot assignment

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  add-to-project:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR to a rotating user
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: gestchild,davidpmccormick,rcantin-w
          numOfAssignee: 1