name: 'Pa11y'
on:
  push:
    branches:
      - pa11y-wf
  schedule:
    - cron: '0 4 * * MON-FRI'
  # Allows external webhook trigger
  repository_dispatch:
    types: [prod_deployment]

permissions:
  id-token: write

jobs:
  pa11y_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Write pa11y report
        run: cd pa11y/webapp && yarn && yarn write-report
  pa11y_deployment:
    runs-on: ubuntu-latest    
    needs:
      - pa11y_report
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.EXPERIENCE_GHA_ROLE_ARN }}
      - name: Upload report to S3
        run: cd pa11y/webapp && yarn deploy
      - name: Complete deployment
        run: echo "${{ github.event.deployment.environment }} complete!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          