# Automatically mark any pull requests that have been inactive for 30 days as "Stale"
# then close them 3 days later if there is still no activity.
#
name: "Stale PR Handler"

on:
  schedule:
    # Check for Stale PRs every Monday to Thursday morning
    # Don't check on Fridays as it wouldn't be very nice to have a bot mark your PR as Stale on Friday and then close it on Monday morning!
    - cron: "0 6 * * MON-THU"

permissions:
  pull-requests: write

jobs:
  stale:
    uses: wellcomecollection/.github/.github/workflows/stale.yml@main