name: "Typescript"
on:
  push:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install Node
      # https://github.com/actions/setup-node?tab=readme-ov-file#usage
      # The node-version input is optional. If not supplied, the node version from PATH will be used.
      # However, it is recommended to always specify Node.js version and don't rely on the system one.
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: (Workspaces) yarn tsc
      run: yarn install && yarn tsc
    - name: (Playwright) yarn tsc
      run: cd playwright && yarn install && yarn tsc
    - name: (Dash) yarn tsc
      run: cd dash/webapp && yarn install && yarn tsc
    - name: (Updown) yarn tsc
      run: cd updown && yarn install && yarn tsc