name: "Typescript"
on:
  push:

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install Node
      # https://github.com/actions/setup-node?tab=readme-ov-file#usage
      # The node-version input is optional. If not supplied, the node version from PATH will be used.
      # However, it is recommended to always specify Node.js version and don't rely on the system one.
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          workspaces:
            - 'cardigan/**'
            - 'common/**'
            - 'content/**'
            - 'identity/**'
            - 'prismic-model/**'
            - 'toggles/**'
            - 'package.json'
            - 'yarn.lock'
          playwright:
            - 'playwright/**' 
          dash:
            - 'dash/**'
          updown:
            - 'updown/**'

    # run only if 'workspaces' files were changed
    - name: workspaces tsc
      if: steps.filter.outputs.workspaces == 'true'
      run: yarn install && yarn tsc

    # run only if 'playwright' files were changed
    - name: playwright tsc
      if: steps.filter.outputs.playwright == 'true'
      run: cd playwright && yarn install && yarn tsc

    # run only if 'dash' files were changed
    - name: dash tsc
      if: steps.filter.outputs.dash == 'true'
      run: cd dash/webapp && yarn install && yarn tsc

    # run only if 'updown' files were changed
    - name: updown tsc
      if: steps.filter.outputs.updown == 'true'
      run: cd updown && yarn install && yarn tsc